g_end_talk="(End conversation)"
g_story_start_full_scrn_text="You slowly open your eyes, dizziness still clouding your mind..."
g_banker_boss_pre_msg="{ilu=tied_in_room}You furtively approach the door, but still struggle to understand the voice speaking within the room beyond. {p}Fortunately, a crack in the old oaken door allows you to peek inside. \n\nOnly a few enemies occupy the room including their leader, fiercly looming in the corner grumbling orders. {p}On the other side of the room a man hangs from a pillar, rawhide cords cruelly eating into his bound wrists. You think to yourself, this might be the banker {u=brian}. \n\nWhat are you going to do now?"

tlks_meet_aileen_1_a="A young woman sits beside you looking down with concern painted over her face. \"Goddess bless, you're finally awake! How do you feel? Do you remember what happened? \""
tlks_meet_aileen_2_q="\"Hmm..... I feel dizzy. Who are you? Did you save me?\""
tlks_meet_aileen_2_a="\"I am {u=aileen}. We found you passed out along the beach. You're an adventurer, aren’t you? But not from this land...\" The lady looks you over and asks, \"Are you here alone or were you with companions?\""
tlks_meet_aileen_3_q="\"We?\""
tlks_meet_aileen_3_a="\"Oh, I’m sorry I forgot to tell you.\" The lady continued, \"My companion {u=tod} and I are both from the Adventurers Guild, we welcome adventurers from the eastern mainland. Perhaps your memory has not yet recovered? This all should have been explained in your invitation letter.\""
tlks_meet_aileen_4_q="\"What is this place?\""
tlks_meet_aileen_4_a="\"This is the nearest beach to {s=41}. {s=41} is not far from here. That is where you should have landed. Let us put aside further questions for now, important tasks lay ahead.\""
tlks_meet_aileen_5_q="\"I came with several adventurers. Did you see them?\""
tlks_meet_aileen_5_a="\"We only found you. My companion {u=tod} has been searching for others, but as of yet has uncovered no clues to where they may be. We must make haste to track them for many monsters wander along this stretch of coastline.\" {u=aileen} anxiously explains, \"We’d better prepare for a fight should you wish to save your companions. Are you ready?\""
tlks_meet_aileen_6_q="\"Yes, let's go at once. I don't want to risk losing any of my friends.\""
tlks_meet_aileen_7_q="\"There is something else that I should figure out.\""
tlks_meet_aileen_7_a="\"All right, but we have no time to waste.\""

tlks_meet_tod_1_a="\"{u=aileen}! Goblin!\" A young fighter rushes at you with two goblins trailing behind. Spears sail over his shoulders and impale the ground just in front of you."
tlks_meet_tod_2_q="Draw your weapons!"
tlks_meet_tod_3_q="\"What? Who are you?\""
tlks_meet_tod_3_a="\"Cut the bullshit, newblood! You take the little one!\" The man rolls his eyes."

tlks_meet_tod_2_1_a="\"These damned goblins!\" The young fighter must be the companion {u=tod} that {u=aileen} mentioned. After cursing the foul little beasts, {u=tod} reports the results of his search, \"Your companions have been taken away by a band of goblins. Unfortunately, the bulk of them broke camp by the time I picked up the trail. I killed two, no, three of them. The rest are no doubt with your friends.\""
tlks_meet_tod_2_2_q="\"How are my companions? Are they hurt??\""
tlks_meet_tod_2_2_a="\"Sorry, I couldn’t see them clearly from such a long distance. They were still on their feet, though, so I doubt any are gravely wounded.\""
tlks_meet_tod_2_3_q="\"What shall we do now?\""
tlks_meet_tod_2_3_a="\"We should move towards {s=227} immediately!\" {u=tod} says hastily, \"If we're lucky we'll reach {s=227} in time to save your companions.\""
tlks_meet_tod_2_4_q="\"Why {s=227}?\""
tlks_meet_tod_2_4_a="\"If they're headed in that direction they could only be bringing your friends to their lair {s=227}. The place crawls with goblins, but the guild can't spare the manpower to slay them all.\""
tlks_meet_tod_2_5_q="\"OK, let’s head to {s=227}!\""

tlks_meet_thomas_1_a="After the battle, the man who looks like a soldier or maybe a guard exits the room, \"Thank you! These monsters would have surely broken through the door without your help.\""
tlks_meet_thomas_2_q="\"We are adventurers of the Adventurers Guild. What happened?\""
tlks_meet_thomas_2_a="\"I’m {u=thomas}, one of {u=brian} the banker's guards. We were ambushed on our way to {s=76}. My companion, {u=william}, and I were trapped in the building by monsters during the evacuation.\""
tlks_meet_thomas_3_q="\"Who are those monsters?\""
tlks_meet_thomas_3_a="\"They are halfling thieves!\" {u=thomas} replies bitterly, \"It’s strange to see skeleton warriors and skeleton archers present.\""
tlks_meet_thomas_4_q="\"Why strange? I thought them to be common monsters.\""
tlks_meet_thomas_4_a="\"Weak undead creatures like skeletons and zombies are not rare, but they should be among their own wretched kind. I’ve never seen such undead fiends work alongside the civilized races before.\" {u=thomas} shakes his head displaying a bitter smile, \"I don’t know what’s going on with this world.\""
tlks_meet_thomas_5_q="\"So you know about the undead?\""
tlks_meet_thomas_5_a="\"Haha! I'm no expert.\", {u=thomas} responds, \"Actually, my uncle was a cleric and he taught me a few things about them as a boy. Basics tactics like using blunt weapons against skeletons. As a cleric he even possessed the ability to turn the undead, though you can't teach faith.\""
tlks_meet_thomas_6_q="\"Where is the banker, {u=brian}, now?\""
tlks_meet_thomas_6_a="\"Most of the guards escorted {u=brian} during the evacuation towards {s=138}. However, with so many enemies about, I've got a bad feeling.\""
tlks_meet_thomas_7_q="\"We were sent to investigate what happened and provide protection.\""
tlks_meet_thomas_7_a="\"Thank god! I was helpless just now, {u=william} was seriously injured and should be taken immediately to the nearest town. Since you seek to rescue {u=brian}, I can finally breathe a sigh of relief and send {u=william} to the town now.\""
tlks_meet_thomas_8_q="\"Just provide us with all the information you know. Please, it would be of great assistance.\""
tlks_meet_thomas_8_a="\"For sure. {s=138} is here on the map,\" {u=thomas} says while marking the location upon our adventure map. \"Also, I've got a morningstar for you, just in case you encounter skeletons.\""
tlks_meet_thomas_9_q="\"Thank you. We will set off on the rescue at once!\""
tlks_meet_thomas_10_q="\"I've got another question.\""
tlks_meet_thomas_10_a="\"OK.\""

tlks_banker_thank_1_1_a="\"Thank you! I never expected help to come.\" Upon conveying what happened to {u=brian}, he solemnly expresses his gratitude."
tlks_banker_thank_1_2_q="\"Only you survived in your troop?\""
tlks_banker_thank_1_2_a="\"I'm not sure. We were split up and there were so many enemies. Several of my guards were slain and afterwards I was caught by the assailants.\""
tlks_banker_thank_1_3_q="\"Do you know anything about these assailants?\""
tlks_banker_thank_1_3_a="\"I don't know why those halflings would've attack my troops. I didn't hear anything useful upon being caught as they only spoke in their own language.\""
tlks_banker_thank_1_4_q="\"Anything about those skeletons?\""
tlks_banker_thank_1_4_a="\"Ah, I did see several of those midgets ordering some skeletons about in the common tongue. They held onto a strange device as they did it. Some artifact of magic that glowed an evil shade of violet.\""
tlks_banker_thank_1_5_q="\"Our mission is to escort you safely to {s=76}, let's go.\""

tlks_banker_thank_2_1_a="\"Finally, there we are!\" {u=brian} takes a deep breath upon arriving at the gate, \"I didn’t expect this {s=76} trip to be so long and dangerous. I should get ready to set up the first bank on the Alrthia continent. I owe the safe return of my guards to your Adventurers Guild, thanks a lot!\""
tlks_banker_thank_2_2_q="\"What services from the bank? Can adventurers use it?\""
tlks_banker_thank_2_2_a="\"For sure.\" {u=brian} seems refreshed talking about the bank. \"Both law-abiding citizens and brave adventurers are entitled to enjoy our services. Our safe deposit boxes are the most secure way to store your gold.\""
tlks_banker_thank_2_3_q="\"Which city do you have in mind for the first bank?\""
tlks_banker_thank_2_3_a="\"It’s still up in the air, we should consider the final investigation results. I think it might be one of the larger cities, if nothing goes wrong.\""
tlks_banker_thank_2_4_q="\"How many banks are planned to be set up on the Alrthia continent?\""
tlks_banker_thank_2_4_a="\"The more, the better!\" {u=brian} says with a smile, \"Actually, it depends. A few big cities will be selected for operation at the initial stage. If we get good performance, we will gradually expand to more cities.\""
tlks_banker_thank_2_5_q="\"Don’t mention it, it’s our job. Good luck and farewell.\""

qsts_1001_n="Looking for Companions"
qsts_1001_d="You wake up on a strange beach. It turns out that Lady {u=aileen}, a member of Adventurers Guild, saved you while your companions were missing.\n\nMany problems remain to be solved, the most urgent one is to find your companions."
qsts_1001_1_n="Searching the Coastline"
qsts_1001_1_d="Clues may be found by tracing the coastline in your search."
qsts_1001_1_msg="{ilu=beach_srch}While searching along the coastline, you soon find some obvious signs of a struggle written upon the sands of the beach. You see a smattering of messy footprints, some human-size, but most smaller.{p}Fortunately, after further exploration you make a discovery: A backpack buried in the sand and a few scattered potions, your companions' belongings! You use the tracks to determine which direction they headed. Onward!"
qsts_1001_2_n="Moving Onward"
qsts_1001_2_d="The clues indicate that your companions were probably taken away by monsters skulking about the area! You must find them before it’s too late."
qsts_1001_3_n="Monster Den"
qsts_1001_3_d="Your companions have been taken away by a band of goblins. You must head to their lair {s=227} as soon as possible!"
qsts_1001_3_obj_str="Rescue your companions in {s=227}"
qsts_1001_3_msg="{ilu=spikes}{s=227}, as the name describes, can be easily identified even from such a long distance as this.\n\nHowever, there is no time to enjoy the scenery. You find those damned goblins outside the building!{p}They mill about a strange statue preparing something without entering the fortress, leaving your companions practically unguarded.\n\nHere's our chance! With a nod you look at each other and pull out your weapons......."
qsts_1001_3_msg2="{ilu=outpost}Courage and persistence finally pay off. Your companions are rescued with minimal casualties. Let them recuperate in the nearby towns and they'll be good as new.{p}{u=aileen} suggests that you head to {s=26}.\n\n{s=26} is an outpost manned by the Adventurers Guild in the eastern continent. {s=26} is an ideal place to rest and re-supply adventuring parties. {u=aileen} will take care of getting you registered with the Adventurers Guild so that you may follow up with them.{p}Although you and your companions may have a lot of questions, such as what happened to your ship, you don’t have any time to dwell on them.\n\nForeign adventurers ship-wrecked in a strange continent would find heeding {u=aileen}’s advice to be undoubtedly your best and only option at this very moment." 

qsts_1002_n="Outpost"
qsts_1002_d="According to {u=aileen}, you decide to take a break in {s=26}. Meanwhile, {u=aileen} will see to the affairs of getting you checked in to the Adventurers Guild for follow-up."

qsts_1003_n="Necessary Preparation"
qsts_1003_d="Sufficient combat prowess and adequate supplies are essential for a qualified adventure party, no matter what is in front of you."

qsts_1004_n="Newcomer Registration"
qsts_1004_d="{u=aileen} has prepared the necessary procedures for you, and now you can report for duty in {s=63}, the Adventurers Guild Headquarters."

qsts_1005_n="Proving Your Strength"
qsts_1005_d="Welcome to the Adventurers Guild!\n\nWe have already received the report from {u=aileen}, thank you so much for solving this crisis! As you know, an abnormally large number of monsters stalk the continent, maiming and killing innocents. These beasts must be eradicated with the utmost haste.\n\nHowever, before assigning any important quests our rules insist we dispatch parties on some routine missions to test their mettle. This is to make sure they can handle the rigors of the adventuring life.\n\nTip:\nThe reputation value of the adventure party can be enhanced by completing town tasks, while gold pieces can be earned in various ways, such as trade or dungeon exploration, etc.."

qsts_1006_n="Go on Adventures"
qsts_1006_d="Well done! You have proven to be a qualified adventuring party.\n\nNow the guild has some other tutorial quests to help you learn more about the abilities that adventurers need. As your party grows, you'll receive more missions from the guild in the future.\n\nOf course, there is no rush to complete these quests. Most importantly, now you can go on adventures and develop your party freely!\n\n<c=o>(This game is currently in Early Access stage and more game content will be added continuously! Thank you again for your support.\n\n-- Low Magic Studios)</c>"

qsts_1007_n="The Missing Banker"
qsts_1007_d="A well-known banker by the name of {u=brian} was recently invited to our land. He has yet to arrive at his destination in {s=76}, but is several days overdue. Flores was travelling with a formidable accompaniment of guards, but in light of recent monster activity we feel it necessary to send someone to investigate his delay.\n\nThe best starting point for your search has been marked on the map. Please head there as soon as possible. Your mission is to escort {u=brian} back to {s=76} safely."
qsts_1007_1_n="Looking for the Banker"
qsts_1007_1_d="The details of the situation are unclear, however, you should head to the target location as soon as possible."
qsts_1007_1_msg="{ilu=broken_carriage}Upon arriving at the designated place, you find the ruins of a caravan. You see a broken down carriage and scattered supplies. However there is no sign of the banker or his companions.{p}After a further search of the area, no more valuable clues are uncovered.\n\nNow you can only expand the scope of your search by investigating other nearby suspicious sites."
qsts_1007_2_n="Expanding the Scope"
qsts_1007_2_d="The banker and his companions are missing, you decide to investigate suspicious places nearby."
qsts_1007_2_msg="{ilu=outdoor_monsters}As you approach the wild cottage, you can hear the buzzing of activity.\n\nUpon getting closer, you spy several halfling thieves and two skeletons in front of the cabin!{p}At that same moment the monsters spot you and attack!"
qsts_1007_2_false_dst_msg="<f=b7>No trace of the banker or his companions.</f>"
qsts_1007_3_n="The Breath of Death"
qsts_1007_3_d="You get more informative but also more worrisome news from one of the banker’s escorts. Now you must go to the destination and rescue {u=brian}."
qsts_1007_3_msg="{ilu=breath_of_death}With the information obtained from {u=thomas}, you keep searching. The signs of struggle, as well as the unburied remains of combatants, gradually lead you to {s=138}.{p}Upon entering the dungeon, you detect the foul rotting odor of decay and see skeletal fragments strewn all over the stone floor. An ominous feeling compels you to leave at once.{p}However, all signs seem to indicate that {u=brian} is likely being held within. You don’t have many options at this point. According to {u=thomas}’s advice, the best course of action is to prepare the right weapons or means to combat the coming undead menace."
qsts_1007_4_n="Digging Deep"
qsts_1007_4_d="The banker is probably imprisoned in {s=138}! Take your hammer, smash every monster, kick in every cell door, and save {u=brian}!"
qsts_1007_4_obj_str="Searching and rescuing the banker"
qsts_1007_4_msg="{ilu=assassin_escape}As you prepare to clean up the battlefield and rescue {u=brian}, a loud explosion thunders behind you leaving the whole room clouded in a dense smog.....{p}When the choking gas dissipates, you realize with shock that the body of the assassin leader is gone!{p}Afterwards, you search both the room and the surrounding areas thoroughly. You find some loot the enemy left behind as well as a letter but no other helpful information.{p}However, the successful rescue of an innocent is a great victory! Besides, he might know something."

qsts_1007_5_n="Escort"
qsts_1007_5_d="Despite this one victory there are no doubt others in need of help. We can’t afford to get distracted. With an unknown threat lurking in the dark, we must escort {u=brian} to {s=76} as soon as possible."

qsts_1008_n="Part-time Locksmith"
qsts_1008_d="You got several ownerless chests from the guild. If you can open them safely, the items inside will be yours.\n\nHave one or two party members train to learn the Open Lock skill. It will be helpful for your future adventures.\n\nIn addition, you'll need to purchase some lockpicks along the way."

qsts_1009_n="Better Tools"
qsts_1009_d="Using the Disable Device and Open Lock skills requires various tools.\n\nAlthough the simple tool set is merely usable, it’s basically for rookies. For professionals, a set of decent thieves’ tools or even a masterwork tool set are a must have."

qsts_1010_n="The Essential Skill"
qsts_1010_d="For adventurers, the Disable Device skill can be a crucial life-and-death ability for dungeon exploration. It’s definitely not wise to rush into a dungeon full of traps without learning this skill.\n\nIt is recommended to let several high Intelligence party members learn this skill."

qsts_1011_n="The Plight of Artisans"
qsts_1011_d="The nearby Artisans Guild has encountered some serious setbacks and is asking for the Adventurers Guild to help. Your party is being sent to aid them."
qsts_1011_1_n="Urgent Situation"
qsts_1011_1_d="Go to the location of Artisans Guild as soon as possible!"
qsts_1011_2_n="Reinstatement of Resource Supply"
qsts_1011_2_d="At present, the biggest problem the artisans are facing is a serious shortage of raw materials. This is because the resource sites are occupied by monsters. Please restore some of these sites as quickly as possible to solve this urgent need."
qsts_1011_3_n="Help others to the end"
qsts_1011_3_d="The resource sites have been successfully reclaimed, but the raw material supply gap is too overwhelming. The Artisans Guild asks you to help gather some urgently needed raw materials. \n\nThe Artisans Guild provides training services for related skills."
qsts_1011_4_n="Gathering Resources"
qsts_1011_4_d="Generally speaking, various kinds of raw materials need to be gathered at different resource sites. Sometimes, however, a small amount of other kinds of raw materials can also be found at these sites."

qsts_1012_n="Skillful Craftsman"
qsts_1012_d="Although ordinary adventurers can find common equipment virtually everywhere, more suitable or high quality equipment is not so easy to obtain.\n\nAfter successfully assisting the Artisans Guild to solve a series of problems, the Adventurers Guild decided to let you learn various equipment crafting skills from the Artisans Guild to help solve the equipment shortage problem of new adventurers."
qsts_1012_1_n="Steel and Fire"
qsts_1012_1_d="Quality equipment comes from quality materials! Familiar with the craftsmanship of various materials is a required course to become a qualified craftsman."
qsts_1012_2_n="Craftsman’s Spirit"
qsts_1012_2_d="Craft a batch of high-quality equipment and deliver it to the Adventurers Guild."

-- z_add_qst.2