g_end_talk="(Fine conversazione)"
g_story_start_full_scrn_text="Apri gli occhi lentamente, le vertigini ancora offuscano i tuoi pensieri......."
g_banker_boss_pre_msg="{ilu=tied_in_room}Ti avvicini furtivamente alla porta, ma fatichi ancora a comprendere le voci che provengono dalla stanza adiacente. {p}Fortunatamente, una crepa nella vecchia porta di quercia permette di sbirciare all'interno. \n\nSolo pochi nemici occupavano la stanza oltre al loro capo, che si stagliava fiero nell'angolo mentre brontolava ordini. {p}Dall'altro lato della stanza, un uomo pendeva da una colonna, con corde di pelle grezza che gli consumavano crudelmente i polsi legati. Tra te e te pensi che potrebbe essere il banchiere {u=brian}. \n\nCosa intendi fare ora?"

tlks_meet_aileen_1_a="Una giovane donna seduta accanto a te con lo sguardo rivolto verso il basso e la preoccupazione dipinta sul viso, \"Che la dea sia benedetta, finalmente ti sei svegliato. Come ti senti? Ti ricordi cosa è successo? \""
tlks_meet_aileen_2_q="\"Hmm..... Ho le vertigini. Chi sei tu? Mi hai salvato?\""
tlks_meet_aileen_2_a="\"Sono {u=aileen}. Ti abbiamo trovato svenuto sulla spiaggia. Sei un avventuriero, vero? Ma non sei di queste terre...\" La donna guardò oltre e chiese, \"Sei qui da solo o con i tuoi compagni?\""
tlks_meet_aileen_3_q="\"Ti...?\""
tlks_meet_aileen_3_a="\"Oh, mi dispiace di aver dimenticato di dirtelo.\" La donna continuò, \"Il mio compagno {u=tod} e io siamo entrambi della Gilda degli Avventurieri, diamo il benvenuto agli avventurieri del continente orientale. Può darsi che tu non abbia ancora recuperato la memoria? Questo potrebbe essere chiarito dalla tua lettera d'invito.\""
tlks_meet_aileen_4_q="\"Cos'è questo posto?\""
tlks_meet_aileen_4_a="\"Questa è la spiaggia più vicina a {s=41}. {s=41} non è molto distante da qui. È lì che avresti dovuto approdare. Mettiamo da parte altre domande, altri compiti importanti ci attendono.\""
tlks_meet_aileen_5_q="\"Sono venuto con diversi avventurieri. Li hai visti?\""
tlks_meet_aileen_5_a="\"Abbiamo trovato solo te. Il mio compagno {u=tod} li ha cercati, ma finora non ha trovato alcun indizio. Dobbiamo affrettarci a rintracciarli perché molti mostri si aggirano lungo questo tratto di costa.\" {u=aileen} disse ansiosamente, \"Sarà meglio prepararsi a combattere se vuoi salvare i tuoi compagni. Sei pronto?\""
tlks_meet_aileen_6_q="\"Sì, andiamo immediatamente. Non voglio rischiare di perdere nessuno dei miei amici.\""
tlks_meet_aileen_7_q="\"C'è qualcos'altro che vorrei capire.\""
tlks_meet_aileen_7_a="\"Va bene, ma non abbiamo tempo da perdere.\""

tlks_meet_tod_1_a="\"{u=aileen}! Goblin!\" Un giovane combattente si precipita verso di te, con due goblin alle spalle. Le lance volano sopra le sue spalle e colpiscono il terreno proprio di fronte a te."
tlks_meet_tod_2_q="Sfoderate le armi!"
tlks_meet_tod_3_q="\"Cosa? Chi sei tu?\""
tlks_meet_tod_3_a="\"Basta con le stronzate, novellino! Prenditi il piccolo!\" L'uomo alzò gli occhi."

tlks_meet_tod_2_1_a="\"Questi maledetti goblin!\" Il giovane guerriero dovrebbe essere il compagno {u=tod} che {u=aileen} ha menzionato. Dopo aver maledetto le piccole bestie ripugnanti, {u=tod} riferì i risultati delle sue ricerche, \"I tuoi compagni sono stati portati via da una banda di goblin. Sfortunatamente, la maggior parte di loro ha lasciato il campo quando ho individuato le tracce. Ho ucciso due, no, tre di loro. Il resto è sicuramente con i tuoi amici.\""
tlks_meet_tod_2_2_q="\"Come stanno i miei compagni? Sono feriti?\""
tlks_meet_tod_2_2_a="\"Mi dispiace, non ho potuto vederli chiaramente da una distanza così grande. Erano ancora in piedi, però, quindi dubito che qualcuno sia gravemente ferito.\""
tlks_meet_tod_2_3_q="\"Cosa dobbiamo fare ora?\""
tlks_meet_tod_2_3_a="\"Dovremmo muoverci verso {s=227} immediatamente!\" {u=tod} disse frettolosamente, \"Se siamo fortunati raggiungeremo {s=227} in tempo per salvare i tuoi amici.\""
tlks_meet_tod_2_4_q="\"Perché {s=227}?\""
tlks_meet_tod_2_4_a="\"Se sono diretti in quella direzione, non possono far altro che portare i tuoi amici nel loro covo nella {s=227}. Il posto brulica di goblin, ma la gilda non ha abbastanza uomini per ucciderli tutti.\""
tlks_meet_tod_2_5_q="\"Ok, dirigiamoci verso {s=227}!\""

tlks_meet_thomas_1_a="Dopo la battaglia, l'uomo che sembrava un soldato o forse una guardia uscì dalla stanza, \"Grazie! Questi mostri avrebbero sicuramente sfondato la porta senza il vostro aiuto.\""
tlks_meet_thomas_2_q="\"Siamo avventurieri della Gilda degli Avventurieri. Che cosa è successo?\""
tlks_meet_thomas_2_a="\"Sono {u=thomas}, una delle guardie del banchiere {u=brian}. Ci hanno teso un'imboscata mentre andavamo a {s=76}, io e il mio compagno {u=william} siamo rimasti intrappolati dai mostri nell'edificio durante l'evacuazione.\""
tlks_meet_thomas_3_q="\"Chi sono questi mostri?\""
tlks_meet_thomas_3_a="\"Sono ladri halfling!\" {u=thomas} rispose amaramente, \"È strano vedere la presenza di guerrieri e arcieri scheletrici.\""
tlks_meet_thomas_4_q="\"Perché strano? Pensavo che fossero dei comuni mostri.\""
tlks_meet_thomas_4_a="\"Le deboli creature non-morte come gli scheletri e gli zombie non sono rare, ma dovrebbero trovarsi tra i loro stessi miserabili simili. Non ho mai visto simili esseri non-morti collaborare con le razze civilizzate prima d'ora.\" {u=thomas} scosse la testa mostrando un amaro sorriso, \"Non so cosa stia succedendo in questo mondo.\""
tlks_meet_thomas_5_q="\"Quindi conosci i non morti?\""
tlks_meet_thomas_5_a="\"Haha! Questo non è esatto\", disse {u=thomas} smentendo le tue teorie, \"Non in questo senso. In realtà mio zio era un chierico e mi ha insegnato alcune cose su di loro da ragazzo. Strategie di base come l'uso di armi contundenti contro gli scheletri. Come chierico possedeva anche la capacità di scacciare i non morti, nonostante non si possa insegnare la fede.\""
tlks_meet_thomas_6_q="\"Dov'è ora il banchiere {u=brian}?\""
tlks_meet_thomas_6_a="\"La maggior parte delle guardie scortò {u=brian} e si diresse verso {s=138}, tuttavia, con così tanti nemici, ebbi un brutto presentimento.\""
tlks_meet_thomas_7_q="\"Siamo stati mandati per indagare e proteggervi.\""
tlks_meet_thomas_7_a="\"Grazie a Dio! Ero impotente poco fa, {u=william} era gravemente ferito e doveva essere portato immediatamente nella città più vicina. Visto che hai promesso di salvare {u=brian}, posso finalmente tirare un sospiro di sollievo e portare {u=william} in città adesso.\""
tlks_meet_thomas_8_q="\"Dacci solo tutte le informazioni di cui sei a conoscenza. Per favore, sarebbe di grande aiuto.\""
tlks_meet_thomas_8_a="\"Certamente. {s=138} è qui sulla mappa,\" {u=thomas} disse segnando il luogo sulla nostra mappa dell'avventura. \"Inoltre, ho una mazza ferrata per te, nel caso in cui ci siano degli scheletri.\""
tlks_meet_thomas_9_q="\"Grazie. Partiremo subito per il salvataggio!\""
tlks_meet_thomas_10_q="\"Ho un'altra domanda.\""
tlks_meet_thomas_10_a="\"OK.\""

tlks_banker_thank_1_1_a="\"Grazie! Non mi aspettavo che arrivasse un aiuto.\" Dopo aver raccontato l'accaduto a {u=brian}, questi espresse solennemente la sua gratitudine."
tlks_banker_thank_1_2_q="\"Solo tu sei sopravvissuto nella tua compagnia?\""
tlks_banker_thank_1_2_a="\"Non ne sono sicuro. Eravamo divisi e c'erano tanti nemici. Diverse delle mie guardie sono state uccise e dopo sono stato catturato dagli assalitori.\""
tlks_banker_thank_1_3_q="\"Sai qualcosa degli aggressori?\""
tlks_banker_thank_1_3_a="\"Non so perché quegli halfling abbiano attaccato le mie truppe, e non ho sentito nulla di utile al momento della cattura, visto che parlavano solo nella loro lingua.\""
tlks_banker_thank_1_4_q="\"Hai visto qualcosa riguardo agli scheletri?\""
tlks_banker_thank_1_4_a="\"In effetti ho visto parecchi di quei nanerottoli che davano ordini ai loro scheletri nella lingua comune. Mentre lo facevano, tenevano in mano uno strano congegno. Un qualche artefatto magico che brillava di una malvagia tonalità violacea.\""
tlks_banker_thank_1_5_q="\"La nostra missione è di scortarti in sicurezza fino a {s=76}, andiamo.\""

tlks_banker_thank_2_1_a="\"Finalmente ci siamo!\" {u=brian} fece un profondo respiro all'arrivo davanti al cancello, \"Non mi aspettavo che questo viaggio verso {s=76} fosse così lungo e pericoloso. Dovrei prepararmi ad allestire la prima banca nel continente di Alrthia. Debbo il ritorno in sicurezza delle mie guardie alla vostra Gilda degli Avventurieri, grazie mille!\""
tlks_banker_thank_2_2_q="\"Quali sono i servizi della banca? Gli avventurieri possono usarla?\""
tlks_banker_thank_2_2_a="\"Certamente.\" {u=brian} si rinvigorì parlando della banca, \"Sia i cittadini rispettosi della legge che gli avventurieri coraggiosi hanno diritto di usufruire dei nostri servizi. Le nostre cassette di sicurezza sono il modo più sicuro per conservare il tuo oro.\""
tlks_banker_thank_2_3_q="\"Quale sarà la città della prima banca?\""
tlks_banker_thank_2_3_a="\"Non è ancora sicuro, dovremmo considerare i risultati dell'indagine finale. Penso che potrebbe essere una delle città più grandi, se nulla va storto.\""
tlks_banker_thank_2_4_q="\"Quante banche sono previste nel continente di Alrthia?\""
tlks_banker_thank_2_4_a="\"Più sono, meglio è!\" {u=brian} disse con un sorriso, \"In realtà, dipende. Alcune grandi città saranno selezionate per le operazioni nella fase iniziale. Se otterremo buoni risultati, gradualmente ci amplieremo in altre città.\""
tlks_banker_thank_2_5_q="\"Non parlarne, è il nostro lavoro. Buona fortuna e addio.\""

qsts_1001_n="Alla ricerca dei compagni"
qsts_1001_d="Ti risvegli su una strana spiaggia. Sembra che Lady {u=aileen}, un membro della Gilda degli Avventurieri, ti abbia salvato mentre i tuoi compagni sono scomparsi.\n\nCon diversi problemi da risolvere, il più urgente è ritrovare i tuoi compagni."
qsts_1001_1_n="Ricerca lungo la costa"
qsts_1001_1_d="È possibile trovare degli indizi cercando lungo la linea della costa."
qsts_1001_1_msg="{ilu=beach_srch}Mentre stai cercando lungo la costa, ben presto ritrovi alcune tracce evidenti di una lotta impressa sulla sabbia della spiaggia. Vedi una manciata di impronte confuse, alcune a misura d'uomo, ma la maggior parte più piccole.{p}Fortunatamente, dopo un'ulteriore esplorazione, fai una scoperta: uno zaino sepolto sotto la sabbia e alcune pozioni sparse, gli effetti personali dei tuoi compagni! Utilizzi le tracce per determinare la direzione in cui si sono diretti. Avanti!"
qsts_1001_2_n="La ricerca continua"
qsts_1001_2_d="Gli indizi indicano che i tuoi compagni sono stati probabilmente portati via da mostri che si aggirano nella zona! Devi trovarli prima che sia troppo tardi."
qsts_1001_3_n="Tana dei mostri"
qsts_1001_3_d="I tuoi compagni sono stati portati via da una banda di goblin. Devi dirigerti verso la loro tana a {s=227} il più presto possibile!"
qsts_1001_3_obj_str="Salva i tuoi compagni a {s=227}"
qsts_1001_3_msg="{ilu=spikes}{s=227}, come descrive il nome, la costruzione può essere facilmente identificata da una grande distanza.\n\nTuttavia, non c'è tempo per godersi il paesaggio. Trovi quei maledetti goblin al di fuori dell'edificio!{p}Si aggirano attorno a una strana statua preparando qualcosa senza entrare nella fortezza, lasciando praticamente incustoditi i tuoi compagni.\n\nLa migliore occasione! Vi guardate e tirate fuori le vostre armi......."
qsts_1001_3_msg2="{ilu=outpost}Il coraggio e la persistenza alla fine pagano. I tuoi compagni sono in salvo con lievi ferite. Falli riposare nelle città vicine e saranno come nuovi.{p}{u=aileen} ti suggerisce di andare a {s=26}.\n\n{s=26} è un avamposto gestito dalla Gilda degli Avventurieri nel continente orientale. {s=26} dovrebbe essere un luogo ideale per il riposo e i rifornimenti per i gruppi di avventurieri, inoltre, {u=aileen} sarà lì a preparare i successivi documenti di registrazione della Gilda degli Avventurieri per te.{p}Anche se tu e i tuoi compagni avete molte domande, come ad esempio cosa è successo alla vostra nave, non avete tempo per pensarci.\n\nAvventurieri stranieri naufragati in un continente sconosciuto, ascoltare il consiglio di {u=aileen} è senza dubbio la vostra migliore e unica opzione in questo momento." 

qsts_1002_n="Avamposto"
qsts_1002_d="In accordo con {u=aileen}, decidi di fare una pausa a {s=26}. Nel frattempo, {u=aileen} preparerà per te i successivi incarichi della Gilda degli Avventurieri."

qsts_1003_n="Preparazione necessaria"
qsts_1003_d="Un'abilità di combattimento sufficiente e provviste adeguate sono essenziali per un gruppo d'avventura qualificato, indipendentemente da ciò che si trova di fronte."

qsts_1004_n="Registrazione dei novizi"
qsts_1004_d="{u=aileen} ha preparato le procedure necessarie per te, e ora puoi fare rapporto per gli incarichi a {s=63}, il quartier generale della Gilda degli Avventurieri."

qsts_1005_n="Prova di forza"
qsts_1005_d="Benvenuto nella Gilda degli Avventurieri!\n\nAbbiamo già ricevuto il rapporto di {u=aileen}, grazie mille per aver sistemato questa faccenda! Come ben sai, un numero abnorme di mostri si aggira per il continente, mutilando e uccidendo innocenti. Queste bestie devono essere sradicate con la massima urgenza.\n\nTuttavia, prima di assegnare missioni importanti, le nostre regole esigono di inviare i gruppi in alcune missioni di routine per assicurarsi che possano gestire i sacrifici della vita d'avventura.\n\nSuggerimento:\nLa reputazione del gruppo d'avventura può essere aumentata completando gli incarichi in città, mentre i pezzi d'oro possono essere guadagnati in vari modi, come il commercio o l'esplorazione dei dungeon, ecc."

qsts_1006_n="All'insegna delle avventure"
qsts_1006_d="Complimenti! Avete dimostrato di essere un gruppo d'avventura competente.\n\nOra la gilda offre alcune altre missioni guida per aiutare a imparare più abilità di cui gli avventurieri hanno bisogno. Man mano che il gruppo cresce, in futuro si riceveranno altre missioni dalla gilda.\n\nNaturalmente, non c'è fretta nel completare queste missioni. La cosa più importante è che ora puoi andare all'avventura e migliorare il tuo gruppo liberamente!\n\n<c=o>(Questo gioco è attualmente in fase di Early Access e altri contenuti saranno aggiunti continuamente! Grazie ancora per il vostro supporto.\n\n-- Low Magic Studios)</c>"

qsts_1007_n="Il banchiere scomparso"
qsts_1007_d="Il noto banchiere {u=brian}, che è stato invitato recentemente nella nostra terra, non è ancora arrivato a destinazione, a {s=76}. È in ritardo di diversi giorni. Nonostante sia accompagnato da un formidabile gruppo di guardie, alla luce della recente attività dei mostri, riteniamo necessario inviare un gruppo per indagare.\n\nSulla mappa è stato segnato il miglior punto di partenza per la tua ricerca, per favore dirigiti lì il prima possibile. La tua missione è di scortare {u=brian} a {s=76} in modo sicuro."
qsts_1007_1_n="Alla ricerca del banchiere"
qsts_1007_1_d="I dettagli della situazione non sono chiari, in ogni caso, dovresti dirigerti verso il luogo dell'obiettivo immediatamente."
qsts_1007_1_msg="{ilu=broken_carriage}Arrivando al luogo stabilito, trovi le tracce di una carovana: una carrozza in panne e provviste sparse. Tuttavia non c'è traccia del banchiere e dei suoi compagni.{p}Dopo ulteriori ricerche, nessun ulteriore indizio di valore è stato scoperto.\n\nOra puoi solo espandere il raggio d'azione della tua ricerca indagando in altri luoghi sospetti nelle vicinanze."
qsts_1007_2_n="Espandere il campo d'azione"
qsts_1007_2_d="Il banchiere e i suoi compagni sono scomparsi, decidi di indagare in luoghi sospetti nelle vicinanze."
qsts_1007_2_msg="{ilu=outdoor_monsters}Prima di raggiungere il capanno di caccia, si poteva sentire il frusciare.\n\nAvvicinandoti, noti diversi ladri halfling e due scheletri di fronte al capanno! Mentre ti avvicini, i mostri ti individuano e ti attaccano!"
qsts_1007_2_false_dst_msg="<f=b7>Nessuna traccia del banchiere e dei suoi compagni.</f>"
qsts_1007_3_n="Il Respiro della Morte"
qsts_1007_3_d="Ottieni notizie più dettagliate ma anche più preoccupanti da uno degli uomini di scorta del banchiere. Ora devi raggiungere la destinazione e salvare {u=brian}."
qsts_1007_3_msg="{ilu=breath_of_death}Con le informazioni ottenute da {u=thomas}, continui a cercare. I segni della battaglia, così come i corpi di entrambe le parti ti portano progressivamente a {s=138}.{p}Entrando nel dungeon, senti il cattivo odore della decomposizione e vedi frammenti di scheletri sparsi sul pavimento di pietra. Una brutta sensazione ti obbliga ad andartene subito.{p}Tuttavia, i segni indicano che {u=brian} è probabilmente rinchiuso all'interno. Non hai molte opzioni ora. Secondo il consiglio di {u=thomas}, la scelta migliore è preparare le armi o i mezzi giusti per combattere la minaccia dei non morti in arrivo."
qsts_1007_4_n="Scavare in profondità"
qsts_1007_4_d="Il banchiere è probabilmente imprigionato a {s=138}! Prendi il tuo martello, distruggi ogni mostro, sfonda ogni porta delle celle e salva {u=brian}!"
qsts_1007_4_obj_str="Trovare e salvare il banchiere"
qsts_1007_4_msg="{ilu=assassin_escape}Mentre ti prepari a ripulire il campo di battaglia e a salvare {u=brian}, una forte esplosione rimbomba alle tue spalle, lasciando l'intera stanza avvolta in un denso fumo.....{p}Quando il fumo soffocante si disperde, ti rendi conto con sgomento che il corpo del capo degli assassini non c'è più!{p}In seguito, perlustri accuratamente sia la stanza che le aree circostanti, trovando solo il bottino lasciato dal nemico e una lettera, senza altre informazioni utili.{p}Tuttavia, salvare un innocente è la vittoria più grande! Inoltre, potrebbe sapere qualcosa."

qsts_1007_5_n="Scorta"
qsts_1007_5_d="Nonostante questa vittoria, ci sono senza dubbio altri che hanno bisogno di aiuto. Non possiamo permetterci di distrarci. Con una minaccia sconosciuta in agguato nel buio, dobbiamo scortare {u=brian} a {s=76} il prima possibile."

qsts_1008_n="Fabbro a tempo perso"
qsts_1008_d="Hai ottenuto diversi forzieri che non hanno un proprietario dalla gilda. Se riesci ad aprili in modo appropriato, gli oggetti all'interno saranno tuoi.\n\nLascia che uno o due membri del gruppo imparino l'abilità Scassinare. Sarà utile per le tue future avventure.\n\nInoltre, compra alcuni grimaldelli durante il cammino."

qsts_1009_n="Strumenti migliori"
qsts_1009_d="Usare le abilità Disattivare Congegni e Scassinare richiede vari strumenti.\n\nAnche se gli strumenti semplici sono facilmente utilizzabili, sono fondamentalmente per i principianti. Per i professionisti, un set di attrezzi da scasso decente e anche la versione perfetta sono indispensabili."

qsts_1010_n="L'abilità essenziale"
qsts_1010_d="Per gli avventurieri, l'abilità Disattivare Congegni può essere un'abilità di vita o di morte. Non è sicuramente saggio precipitarsi in un dungeon pieno di trappole senza aver imparato questa abilità.\n\nÈ consigliabile far imparare questa abilità a diversi membri del gruppo dotati di un'intelligenza elevata."

qsts_1011_n="La situazione degli artigiani"
qsts_1011_d="La vicina Gilda degli Artigiani si è trovata in difficoltà e ha dovuto chiedere aiuto alla Gilda degli Avventurieri. Il tuo gruppo è stato incaricato di aiutarli."
qsts_1011_1_n="Situazione urgente"
qsts_1011_1_d="Raggiungi il prima possibile il luogo della Gilda degli Artigiani!"
qsts_1011_2_n="Rifornimento di risorse"
qsts_1011_2_d="Attualmente, il più grande problema degli artigiani è che molti luoghi di approvvigionamento di materie prime sono stati occupati da mostri, con conseguente grave carenza dei materiali grezzi. È necessario ripristinare alcuni luoghi di risorse il più rapidamente possibile per risolvere le urgenti necessità."
qsts_1011_3_n="Aiuta gli altri fino alla fine"
qsts_1011_3_d="I luoghi delle risorse sono stati risanati con successo! Ma il fabbisogno di materie prime è troppo grande. La Gilda degli Artigiani ti chiede di aiutare a raccogliere alcune materie grezze indispensabili. \n\nLa Gilda degli Artigiani si occupa di servizi di addestramento per le relative competenze."
qsts_1011_4_n="Raccolta di risorse"
qsts_1011_4_d="In generale, diversi tipi di materie prime devono essere raccolte in diversi giacimenti di risorse. Tuttavia, a volte una piccola quantità di altri tipi di materie prime può essere trovata nei giacimenti di risorse."

qsts_1012_n="Abile artigiano"
qsts_1012_d="Per gli avventurieri ordinari, anche se l'attrezzatura comune può essere trovata ovunque, l'attrezzatura di alta qualità e idonea non è facile da ottenere.\n\nDopo aver aiutato con successo la Gilda degli Artigiani a risolvere una serie di problemi, la Gilda degli Avventurieri ha deciso di farti imparare varie abilità di creazione di equipaggiamento alla Gilda degli Artigiani per risolvere il problema della carenza di equipaggiamento dei nuovi avventurieri."
qsts_1012_1_n="Fuoco e acciaio"
qsts_1012_1_d="L'attrezzatura di qualità viene da materiali di qualità! Conoscere l'artigianato dei vari materiali è un requisito necessario per diventare un artigiano qualificato."
qsts_1012_2_n="Spirito artigianale"
qsts_1012_2_d="Realizza una partita di equipaggiamento di alta qualità e consegnala alla Gilda degli Avventurieri."

-- z_add_qst.2