g_end_talk="(Terminar conversación)"
g_story_start_full_scrn_text="Abres los ojos lentamente, la sensación de mareo aún nubla tu mente..."
g_banker_boss_pre_msg="{ilu=tied_in_room}Te aproximas furtivamente a la puerta, pero te sigue costando entender la voz que resuena en la otra habitación. {p}Por fortuna, una rendija en la vieja puerta de roble te permite echar un vistazo al interior.\n\nSolo unos pocos enemigos ocupan la estancia, además de su líder, el cual se asoma amenazante mientras da órdenes.{p}En el otro lado de la habitación, un hombre cuelga de uno de los pilares, con cuerdas de cuero crudo devorando cruelmente sus muñecas. Piensas que podría tratarse del banquero {u=brian}. \n\n¿Qué vas a hacer ahora?"

tlks_meet_aileen_1_a="Una mujer joven está sentada a tu lado, mirando hacia abajo, con la preocupación dibujada en su rostro. \"Gracias a Dios, ¡por fin te has despertado! ¿Cómo te encuentras?¿Recuerdas lo ocurrido? \""
tlks_meet_aileen_2_q="\"Hmm..... Me siento mareado. ¿Quién eres?¿Me has salvado?\""
tlks_meet_aileen_2_a="\"Mi nombre es {u=aileen}. Te encontramos inconsciente en la playa. Tú eres un aventurero, ¿verdad? Pero no de estas tierras.\" La joven te mira ahora y pregunta, \"¿Estás aquí solo o viniste con otros compañeros?\""
tlks_meet_aileen_3_q="\"¿Encontramos?\""
tlks_meet_aileen_3_a="\"Oh, lo siento, no te he dicho nada.\" La joven continuó hablando, \"Mi compañero {u=tod} y yo formamos parte del Gremio de Aventureros, damos la bienvenida a todo tipo de aventureros provenientes del este continental. ¿Quizá tu memoria no se ha recuperado del todo? Todo esto se te debió de explicar en tu carta de invitación.\""
tlks_meet_aileen_4_q="\"¿Qué es este lugar?\""
tlks_meet_aileen_4_a="\"Estamos en la playa más cercana a {s=41}. {s=41}, de hecho, no está lejos de aquí. Es el lugar en el que deberías de estar, pero dejemos de lado el tema por ahora, aún nos queda trabajo importante por hacer.\""
tlks_meet_aileen_5_q="\"Vine con otros aventureros. ¿Los has visto?\""
tlks_meet_aileen_5_a="\"Solo te encontramos a ti. Mi compañero {u=tod} ha seguido buscando a los demás, pero hasta el momento no tenemos ninguna idea de dónde podrían estar. Debemos darnos prisa y encontrarlos, pues muchos monstruos deambulan por este tramo de playa.\" {u=aileen} explica ansiosamente, \"Será mejor que nos preparemos para luchar si quieres salvar a tus compañeros. ¿Estás preparado?\""
tlks_meet_aileen_6_q="\"Sí, salgamos de inmediato. No quiero correr el riesgo de perder a ninguno de mis amigos.\""
tlks_meet_aileen_7_q="\"Hay algo más que me gustaría entender.\""
tlks_meet_aileen_7_a="\"Está bien, pero no tenemos tiempo que perder.\""

tlks_meet_tod_1_a="\"¡{u=aileen}! ¡Goblin!\" Un joven guerrero corre hacia ti con dos goblin justo detrás. Las lanzas vuelan sobre sus hombros y se clavan en el suelo justo enfrente de ti."
tlks_meet_tod_2_q="¡Prepara tus armas!"
tlks_meet_tod_3_q="\"¿Qué?¿Quién eres?\""
tlks_meet_tod_3_a="\"¡Déjate de tonterías, novato!\" El hombre pone sus ojos en blanco."

tlks_meet_tod_2_1_a="\"¡Esos malditos goblin!\" El joven guerrero debe ser {u=tod}, el compañero que {u=aileen} mencionó. Después de maldecir a esas infames bestias pequeñas, {u=tod} informa de los resultados de su búsqueda, \"Una banda de goblin se ha llevado a tus compañeros. Por desgracia, la mayoría levantaron el campamento para cuando descubrí el rastro. Maté a dos, no, a tres de ellos. El resto está, sin lugar a duda, con tus amigos.\""
tlks_meet_tod_2_2_q="\"¿Cómo están mis compañeros?¿Los han herido?\""
tlks_meet_tod_2_2_a="\"Lo siento, me temo que no pude verlos con claridad desde tanta distancia. Podían mantenerse en pie, eso sí, así que dudo que ninguno de ellos esté herido de gravedad.\""
tlks_meet_tod_2_3_q="\"¿Qué deberíamos hacer ahora?\""
tlks_meet_tod_2_3_a="\"¡Deberíamos dirigirnos hacia {s=227} de inmediato!\" Se apresura a decir {u=tod}, \"Si tenemos suerte, llegaremos a {s=227} a tiempo como para salvar a tus compañeros.\""
tlks_meet_tod_2_4_q="\"¿{s=227}?¿Por qué a {s=227}?\""
tlks_meet_tod_2_4_a="\"Si se dirigen en la dirección que se dirigen, solo pueden estar llevándolos hacia su guarida, el {s=227}. Ese lugar está plagado de goblin, pero el gremio no puede pagar el coste humano de acabar con todos ellos.\""
tlks_meet_tod_2_5_q="\"Está bien, ¡A {s=227} entonces!\""

tlks_meet_thomas_1_a="Después de la batalla, el hombre que parece un soldado o, quizá, un guardia, sale de la habitación. \"¡Gracias! Estos monstruos habrían terminado entrando sin tu ayuda.\""
tlks_meet_thomas_2_q="\"Somos del Gremio de Aventureros. ¿Qué ha ocurrido?\""
tlks_meet_thomas_2_a="\"Mi nombre es {u=thomas}, soy uno de los guardias del banquero, {u=brian}. Nos emboscaron cuando nos dirigíamos a {s=76}. Mi compañero, {u=william}, y yo fuimos atrapados por monstruos durante la evacuación.\""
tlks_meet_thomas_3_q="\"¿De qué monstruos hablas?\""
tlks_meet_thomas_3_a="\"¡Son ladrones medianos!\" responde {u=thomas} con amargura, \"Es raro ver la presencia de guerreros y arqueros esqueletos.\""
tlks_meet_thomas_4_q="\"¿Por qué es raro? Pensaba que eran monstruos comunes.\""
tlks_meet_thomas_4_a="\"Las criaturas no muertas, como esqueletos y zombies, no son raras, pero deberían estar entre sus desdichados compañeros. No había visto nunca que los seres no-muertos colaboraran con las razas civilizadas hasta ahora. \" {u=thomas} sacude la cabeza, mostrando una amarga sonrisa, \"No sé qué está pasando en este mundo.\""
tlks_meet_thomas_5_q="\"Entonces, ¿sabes sobre no-muertos?\""
tlks_meet_thomas_5_a="\"¡Haha! No soy ningún experto.\", Responde {u=thomas}, \"De hecho, mi tío era clérigo y me enseñó algunas cosas sobre ellos cuando era niño. Tácticas básicas como usar armas contundentes contra los esqueletos. Como clérigo tenía, incluso, la habilidad de expulsar a los no-muertos, aunque la fe no es algo que se pueda enseñar.\""
tlks_meet_thomas_6_q="\"¿Dónde está el banquero, {u=brian}, ahora mismo?\""
tlks_meet_thomas_6_a="\"La mayoría de los guardias escoltaron a {u=brian} durante la evacuación hacia {s=138}. Sin embargo, con tantos enemigos en los alrededores, tengo un mal presentimiento.\""
tlks_meet_thomas_7_q="\"Nos enviaron a investigar lo ocurrido y a brindar protección.\""
tlks_meet_thomas_7_a="\"¡Gracias a Dios! Me sentí un poco impotente ahora mismo, {u=william} ha sido gravemente herido y debe ser llevado inmediatamente a la ciudad más cercana. Como tienes la intención de rescatar a {u=brian}, puedo tomarme un respiro y enviar a {u=william} a la ciudad.\""
tlks_meet_thomas_8_q="\"Solo dinos toda la información que puedas, por favor. Sería de gran ayuda.\""
tlks_meet_thomas_8_a="\"Por supuesto. El {s=138} está en esta parte del mapa,\" dice {u=thomas} mientras marca la ubicación en tu mapa de aventurero. \"Además, quiero entregarte este lucero del alba, por si te encuentras con algunos de esos esqueletos.\""
tlks_meet_thomas_9_q="\"Te lo agradezco. ¡Partiremos de inmediato!\""
tlks_meet_thomas_10_q="\"Tengo otra pregunta.\""
tlks_meet_thomas_10_a="\"OK.\""

tlks_banker_thank_1_1_a="\"¡Muchas gracias! No esperaba que llegase la ayuda.\" Cuando le cuentas a {u=brian} lo ocurrido, expresa su más solemne gratitud."
tlks_banker_thank_1_2_q="\"¿Eres el único que ha sobrevivido?\""
tlks_banker_thank_1_2_a="\"No estoy seguro. Había muchísimos enemigos y terminamos separándonos. Mataron a varios de mis guardias y, entonces, los asaltantes me capturaron.\""
tlks_banker_thank_1_3_q="\"¿Sabes algo acerca de esos asaltantes?\""
tlks_banker_thank_1_3_a="\"No tengo ni idea de por qué me atacarían esos medianos. No escuché nada útil cuando me atraparon, ya que solo hablaban en su propio idioma.\""
tlks_banker_thank_1_4_q="\"¿Algo sobre los esqueletos?\""
tlks_banker_thank_1_4_a="\"Ah, sí que vi algunos medianos dando órdenes a esqueletos en la lengua común. Se aferraban a un extraño artefacto cuando lo hacían. Uno que brillaba con un fatídico tono violeta.\""
tlks_banker_thank_1_5_q="\"Nuestra misión es asegurarnos de que llegas sano y salvo a {s=76}, pongámonos en marcha.\""

tlks_banker_thank_2_1_a="\"¡Por fin hemos llegado!\" {u=brian} respira profundamente al llegar a las puertas, \"No esperaba que este viaje a {s=76} resultara tan largo y peligroso. Debería prepararme para establecer el primer banco en el continente de Alrthia. Estoy en deuda con vuestro Gremio de Aventureros por devolverme a mis guardias sanos y salvos. ¡Muchas gracias!\""
tlks_banker_thank_2_2_q="\"¿Qué servicios ofrece tu banco?¿Pueden los aventureros darle uso?\""
tlks_banker_thank_2_2_a="\"Claro que sí.\" {u=brian} parece renovado al hablar del banco. \"Tanto los ciudadanos de bien como los valientes aventureros tienen derecho a disfrutar de nuestros servicios. Nuestras cajas de seguridad son las más seguras para guardar tu oro.\""
tlks_banker_thank_2_3_q="\"¿En qué ciudad tienes pensado abrir el primer banco?\""
tlks_banker_thank_2_3_a="\"Eso es algo que está aún en el aire. Debemos considerar los resultados finales de la investigación, pero, si nada sale mal, debería ser una de las grandes ciudades.\""
tlks_banker_thank_2_4_q="\"¿Cuántos bancos planeas abrir en el continente de Alrthia?\""
tlks_banker_thank_2_4_a="\"¡Cuantos más, mejor!\" Dice {u=brian} con una sonrisa, \"En realidad, depende. Se seleccionarán algunas ciudades grandes para la etapa inicial. Si conseguimos un buen resultado en ellas, nos iremos expandiendo a más ciudades.\""
tlks_banker_thank_2_5_q="\"De nada, de nada, es nuestro trabajo. Buena suerte y hasta otra.\""

qsts_1001_n="Buscando Compañeros"
qsts_1001_d="Te despiertas en una playa extraña. Resulta que Lady {u=aileen}, del Gremio de Aventureros, te salvó, si bien tus compañeros están desaparecidos.\n\nQuedan muchos problemas por resolver, y el más urgente de ellos es encontrar a tus compañeros."
qsts_1001_1_n="Investigando la Costa"
qsts_1001_1_d="Se pueden encontrar pistas si investigas la costa."
qsts_1001_1_msg="{ilu=beach_srch}Mientras buscas a lo largo de la costa, terminas por encontrar, dibujado en la arena de la playa, signos evidentes de una lucha. Ves varias huellas desordenadas, algunas de tamaño humano, pero otras son más pequeñas.{p}Por fortuna, conforme sigues investigando vas encontrando nuevas pistas: Una mochila enterrada en la arena y unas pocas pociones esparcidas en la arena, ¡las pertenencias de tus compañeros! Usas el rastro dejado para determinar la dirección en la que siguieron su camino. ¡Adelante!"
qsts_1001_2_n="La Búsqueda Continúa"
qsts_1001_2_d="¡Las pistas indican que tus compañeros fueron probablemente capturados por los monstruos que merodean por la zona! Debes encontrarlos antes de que sea demasiado tarde."
qsts_1001_3_n="Guarida de Monstruos"
qsts_1001_3_d="Un grupo de goblin se ha llevado a tus compañeros. Debes dirigirte a su guarida, el {s=227}, ¡tan pronto como sea posible!"
qsts_1001_3_obj_str="Rescata a tus compañeros en el {s=227}"
qsts_1001_3_msg="{ilu=spikes}El {s=227}, como su nombre indica, puede identificarse fácilmente incluso desde una distancia tan larga como esta.\n\nSin embargo, no hay tiempo de disfrutar de las vistas, ya que encuentras a esos malditos goblin en el exterior del edificio.{p}Se mueven alrededor de una extraña estatua, preparando algo, sin entrar en la fortaleza, y dejando a tus compañeros prácticamente sin vigilancia.\n\n¡Es la oportunidad que estábamos esperando! Con un movimiento de cabeza todos entienden que es hora de sacar las armas..."
qsts_1001_3_msg2="{ilu=outpost}El coraje y la perseverancia dan, finalmente, sus frutos. Tus compañeros han sido rescatados con pocas consecuencias. Deja que se recuperen en los asentamientos cercanos y estarán como nuevos.{p}{u=aileen} sugiere que te dirijas a {s=26}.\n\n{s=26} es un puesto de avanzada atendido por el Gremio de Aventureros en el continente oriental, así como un lugar perfecto para que los grupos de aventureros descanses y se reabastezcan. {u=aileen} se encargará de registrarte en el Gremio de Aventureros para que puedas seguir con ellos.{p}A pesar de que tú y tus compañeros tendréis muchas preguntas, tales como lo que ocurrió con vuestro barco, no tenéis tiempo como para pensar en ellas.\n\nCualquier aventurero extranjero que haya naufragado en un extraño continente consideraría que el consejo de {u=aileen} es, sin lugar a dudas, el mejor curso de acción a seguir en este momento." 

qsts_1002_n="Puesto de Avanzada"
qsts_1002_d="Siguiendo el consejo de {u=aileen}, decides tomarte un descanso en {s=26}. Mientras tanto, {u=aileen} se encargará de que te registren en el Gremio de Aventureros."

qsts_1003_n="Preparativos Necesarios"
qsts_1003_d="Tener suficiente destreza en combate y unos suministros adecuados son esenciales para un grupo de aventureros cualificado, sin importar el camino que vayas a seguir."

qsts_1004_n="Registro en el Gremio"
qsts_1004_d="{u=aileen} ha preparado todo lo necesario en tu nombre y a partir de ahora podrás asumir funciones y encargos en la sede del Gremio de Aventureros, en {s=63}."

qsts_1005_n="Prueba de Fuerza"
qsts_1005_d="¡Bienvenido al Gremio de Aventureros!\n\nYa tenemos aquí el informe de {u=aileen}, ¡gracias por resolver esta crisis! Como sabes, una cantidad anormalmente grande de monstruos merodean por el continente, mutilando y asesinando a inocentes. Esas bestias deben ser erradicadas lo más rápido posible.\n\nSin embargo, antes de poder asignar misiones importantes, nuestras reglas imponen que se asignen algunas misiones rutinarias para poner a prueba el temple de los grupos. Así, podremos asegurarnos de que el grupo puede soportar la vida de aventurero.\n\nConsejo:\nEl valor de la reputación del grupo de aventureros puede mejorarse completando encargos en la ciudad, mientras que el oro puede ganarse de diversas formas, tales como el comercio o la exploración de mazmorras..."

qsts_1006_n="En Busca de Aventuras"
qsts_1006_d="¡Bien hecho! Has demostrado ser un aventurero cualificado.\n\nAhora, el gremio tiene otras misiones de tutorial para ayudarte a aprender más de las aptitudes que todo aventurero necesita. Conforme crezca tu grupo, recibirás más misiones del Gremio.\n\nPor supuesto, no hay ninguna prisa por completar estas misiones. Es más, ¡ahora puedes salir de aventura y desarrollar tu grupo con libertad!\n\n<c=o>(Este juego se encuentra en Acceso Anticipado y ¡se irá añadiendo nuevo contenido continuamente! Gracias por todo el apoyo.\n\n-- Low Magic Studios)</c>"

qsts_1007_n="El Banquero Perdido"
qsts_1007_d="Un reputado banquero llamado {u=brian} ha sido recientemente invitado a nuestras tierras. Aún tiene que llegar a {s=76}, pero se está retrasando más de lo normal. Flores viajaba con una escolta formidable, pero a la luz de la reciente actividad de monstruos sentimos la necesidad de enviar a alguien que investigue este retraso.\n\nHemos marcado en tu mapa el que consideramos que es el mejor punto de partida posible. Dirígete hasta el lugar lo antes posible. Tu misión es traer a {u=brian} a {s=76} sano y salvo."
qsts_1007_1_n="En Busca del Banquero"
qsts_1007_1_d="Los detalles de la situación no están claros, sin embargo, deberías dirigirte a la ubicación objetivo tan pronto como sea posible."
qsts_1007_1_msg="{ilu=broken_carriage}Al llegar al lugar señalado, encuentras los restos de una caravana. Puedes ver el carruaje roto y los suministros esparcidos por el lugar. Sin embargo, no hay rastro del banquero ni de sus acompañantes.{p}Después de una búsqueda más concisa por la zona, determinas que no hay pistas valiosas que descubrir.\n\nSolo te queda ampliar el alcance de la búsqueda a otros sitios sospechosos cercanos."
qsts_1007_2_n="Ampliando la Búsqueda"
qsts_1007_2_d="No has podido encontrar al banquero ni a sus acompañantes, así que decides investigar los lugares sospechosos cercanos."
qsts_1007_2_msg="{ilu=outdoor_monsters}A medida que te acercas a la cabaña de caza, vas distinguiendo un cierto alboroto.\n\nAl estar a una distancia prudencial, observas a varios medianos ladrones y a dos esqueletos frente a la cabaña.{p}En ese mismo momento, los monstruos te detectan y te atacan."
qsts_1007_2_false_dst_msg="<f=b7>No hay rastro del banquero ni de sus acompañantes</f>"
qsts_1007_3_n="El Aliento de la Muerte"
qsts_1007_3_d="Obtienes información más clara pero también más preocupante de uno de los escoltas del banquero. Debes dirigirte a tu destino y rescatar a {u=brian}."
qsts_1007_3_msg="{ilu=breath_of_death}Con la información recibida de {u=thomas}, prosigues la búsqueda. Los signos de lucha, así como los restos sin enterrar de los combatientes, te van conduciendo al {s=138}.{p}Al entrar en la mazmorra, detectas el desagradable olor a descomposición, así como múltiples fragmentos de esqueletos esparcidos por todo el suelo de piedra.{p}Sin embargo, todo parece indicar que, muy posiblemente, retienen a {u=brian} en el interior. Llegados a este punto, no te quedan muchas opciones. Según el consejo de {u=thomas}, el mejor curso de acción es preparar las armas o medios adecuados para combatir la amenaza de no-muertos que se aproxima."
qsts_1007_4_n="Excavar en Profundidad"
qsts_1007_4_d="¡El banquero está probablemente preso en el {s=138}!¡Toma tu martillo, aplasta a todos los monstruos, abre de un golpe todas las puertas y libera a {u=brian}!"
qsts_1007_4_obj_str="Buscando y rescatando al banquero"
qsts_1007_4_msg="{ilu=assassin_escape}En cuanto te preparas para limpiar el campo de batalla y rescatar a {u=brian}, una fuerte explosión resuena detrás de ti, causando que la habitación se llene con una densa niebla tóxica...{p}Cuando este asfixiante gas se disipa, te das cuenta con estupor de que el cuerpo del líder asesino ha desaparecido.{p}Entonces, registras en profundidad tanto la habitación como las zonas colindantes. Encuentras algo de botín que el enemigo dejó atrás, así como una carta, pero no encuentras nada que te revele información importante.{p}Sin embargo, el rescate exitoso de un inocente ¡es una gran victoria! Además, puede que él sí sepa algo."

qsts_1007_5_n="Escolta"
qsts_1007_5_d="A pesar de esta victoria, no hay duda de que habrá otros que necesiten ayuda. No podemos permitirnos caer en distracciones. Con una amenaza desconocida acechando en la oscuridad, debemos escoltar a {u=brian} a {s=76} tan rápido como sea posible."

qsts_1008_n="Cerrajero a Tiempo Parcial"
qsts_1008_d="El gremio te ha entregado varios cofres sin dueño. Si puedes abrirlos de forma segura, el contenido será tuyo.\n\nHaz que uno o dos miembros del grupo entrenen para aprender la aptitud de Abrir Cerradura. Será de gran ayuda para tus viajes en el futuro.\n\nAdemás, necesitarás comprar algunas ganzúas durante tus aventuras."

qsts_1009_n="Herramientas Mejoradas"
qsts_1009_d="Para utilizar las aptitudes de Inutilizar Mecanismo y Abrir Cerradura se requieren distintas herramientas.\n\nAunque el set básico de herramientas se puede utilizar, no deja de ser para novatos. Para los profesionales, es imprescindible llevar un set decente de herramientas de ladrón o incluso herramientas del más alto nivel."

qsts_1010_n="La Habilidad Esencial"
qsts_1010_d="Para los aventureros, la aptitud de Inutilizar Mecanismo puede ser crucial en la exploración de mazmorras, incluso ser la diferencia entre la vida y la muerte. Definitivamente, no es prudente precipitarse a una mazmorra llena de trampas sin tener esta aptitud.\n\nEs recomendable que varios miembros del grupo con alta Inteligencia aprendan esta aptitud."

qsts_1011_n="La Situación de los Artesanos"
qsts_1011_d="El cercano Gremio de Artesanos ha encontrado algunos contratiempos y está requiriendo la ayuda del Gremio de Aventureros. Tu grupo será el encargado de prestarles ayuda."
qsts_1011_1_n="Situación Urgente"
qsts_1011_1_d="¡Ve a la ubicación del Gremio de Artesanos tan pronto como sea posible!"
qsts_1011_2_n="Restableciendo las Rutas de Suministros"
qsts_1011_2_d="En la actualidad, el mayor problema al que se enfrentan los artesanos es la escasez de materias primas. Esto se debe a que los lugares de donde provienen han sido ocupados por los monstruos. Por favor, restablece el normal funcionamiento de estos sitios tan pronto como sea posible para resolver esta urgente necesidad."
qsts_1011_3_n="Ayudando hasta el final"
qsts_1011_3_d="Has reclamado con éxito los yacimientos de recursos, pero la falta de suministro de materia prima es demasiado acuciada. El Gremio de Artesanos te pide recolectar algunas materias primas de urgente necesidad.\n\nEl Gremio de Artesanos se encargará de proporcionar un servicio de entrenamiento de las aptitudes necesarias."
qsts_1011_4_n="Recolectando Recursos"
qsts_1011_4_d="En general, es necesario reunir diversos tipos de materias primas, provenientes de distintos yacimientos. A veces, sin embargo, una pequeña cantidad de otros tipos de materiales pueden encontrarse en dichos yacimientos."

qsts_1012_n="Artesano Hábil"
qsts_1012_d="Aunque los aventureros comunes pueden encontrar equipo común prácticamente en cualquier lado, el equipo más especializado o de más calidad no es tan fácil de obtener.\n\nDespués de ayudar al Gremio de Artesanos a resolver algunos problemas, el Gremio de Aventureros ha decidido permitir que aprendas varias aptitudes de fabricación de equipamiento del propio Gremio de Artesanos, para poder ayudar a resolver el problema de la carencia de equipamiento para nuevos aventureros."
qsts_1012_1_n="Fuego y Acero"
qsts_1012_1_d="¡Un equipamiento de calidad requiere de materiales de calidad! Estar familiarizado con la artesanía de distintos materiales es un requisito fundamental para llegar a ser un artesano cualificado."
qsts_1012_2_n="Espíritu de Artesano"
qsts_1012_2_d="Fabrica un lote de equipamiento de alta calidad y entrégalo en el Gremio de Aventureros."

-- z_add_qst.2