g_end_talk="(Fin de la conversation)"
g_story_start_full_scrn_text="Vous ouvrez lentement les yeux, mais un léger vertige rend encore confus vos pensées..."
g_banker_boss_pre_msg="{ilu=tied_in_room}Vous vous approchez discrètement de la porte, mais vous avez encore des difficultés à bien comprendre ce qui dit la voix de l'autre côté. {p}Par chance, une fissure dans la vieille porte en chêne vous permet de jeter un coup d'œil dans la pièce voisine. \n\nVous apercevez plusieurs hommes en plus de celui qui semble être leur chef. Ce dernier se tient dans un coin, semblant retenir sa colère tout en grommelant des ordres. {p}À l'autre bout de la salle, un homme est attaché à un pilier, une corde en cuir brut lui entaillant cruellement les poignets. Vous vous dites qu'il pourrait s'agir du banquier {u=brian}. \n\nEt maintenant, que comptez-vous faire ?"

tlks_meet_aileen_1_a="Une jeune femme est assise à vos côtés, la tête penchée en avant, l'inquiétude se lisant sur son visage, \"Louée soit la déesse, tu es enfin réveillé(e). Comment te sens-tu ? Te souviens-tu de ce qui s'est passé ? \""
tlks_meet_aileen_2_q="\"Humm... Je me sens étourdi(e). Qui es-tu ? Est-ce toi qui m'a sauvé(e) ?\""
tlks_meet_aileen_2_a="\"Je m'appelle {u=aileen}. Nous t'avons trouvé(e) évanoui(e) sur la plage. Tu es un(e) aventurier(ère), n'est-ce pas ? Mais tu n'es pas d'ici...\" La femme vous examine un instant avant de demander, \"Étais-tu seul(e) ou avec des compagnons ?\""
tlks_meet_aileen_3_q="\"Nous ?\""
tlks_meet_aileen_3_a="\"Oh, je suis désolée, j'ai oublié de te le dire.\" Et la femme poursuit, \"Mon compagnon {u=tod} et moi appartenons tous les deux à la guilde des aventuriers, et notre tâche est d'accueillir les nouveaux qui arrivent de l'est du continent. Mais peut-être que ta mémoire n'est pas encore complètement revenue ? Tout ça a dû t'être expliqué dans ta lettre d'invitation.\""
tlks_meet_aileen_4_q="\"Quel est cet endroit ?\""
tlks_meet_aileen_4_a="\"Nous nous trouvons à proximité de la place de {s=41}. {s=41} n'est pas loin d'ici. C'est là-bas que tu aurais dû débarquer. Laissons de côté les questions pour le moment, car des tâches urgentes nous attendent.\""
tlks_meet_aileen_5_q="\"Il y avait d'autres aventuriers avec moi. Les avez-vous aperçus ?\""
tlks_meet_aileen_5_a="\"Non, nous n'avons trouvé que toi. Mon compagnon {u=tod} les a cherchés, mais il n'a toujours pas repéré de traces de leur présence. Nous devrions nous dépêcher de les localiser, car de nombreux monstres errent le long de cette partie de la côte.\" Puis {u=aileen} rajouta avec une certaine anxiété, \"Nous devrions être sur nos gardes si tu veux sauver tes compagnons. Es-tu prêt(e) ?\""
tlks_meet_aileen_6_q="\"Oui, partons maintenant. Je ne veux pas prendre le risque de perdre mes amis.\""
tlks_meet_aileen_7_q="\"Il y a autre chose que j'aimerais comprendre.\""
tlks_meet_aileen_7_a="\"D'accord, mais nous n'avons pas de temps à perdre.\""

tlks_meet_tod_1_a="\"{u=aileen} ! Des gobelins !\" crie un jeune combattant fonçant dans votre direction, deux gobelins le poursuivant. Plusieurs lances volent au-dessus de ses épaules et s'enfoncent dans le sol juste devant vous."
tlks_meet_tod_2_q="Sortez votre arme !"
tlks_meet_tod_3_q="\"Comment ça ? Qui es-tu ?\""
tlks_meet_tod_3_a="\"Arrête tes conneries, le nouveau ! Occupes-toi du petit !\" dit l'homme en levant les yeux au ciel avec exaspération."

tlks_meet_tod_2_1_a="\"Maudits gobelins !\" Le jeune combattant doit être {u=tod}, le compagnon mentionné par {u=aileen}. Après avoir maudit les infâmes petites créatures, {u=tod} vous fait part des résultats de ses recherches, \"Vos compagnons ont été emmenés par une bande de gobelins. Malheureusement, la plupart d'entre eux avaient déjà quitté leur campement. J'en ai tué deux, non, trois, mais les autres sont sans doute partis avec vos amis.\""
tlks_meet_tod_2_2_q="\"Comment vont mes compagnons ? Sont-ils blessés ?\""
tlks_meet_tod_2_2_a="\"Désolé, mais je ne pouvais pas les voir distinctement de si loin. Mais ils étaient tous debout, aussi je doute qu'il y ait des blessés graves.\""
tlks_meet_tod_2_3_q="\"Qu'allons-nous faire maintenant ?\""
tlks_meet_tod_2_3_a="\"Nous devrions nous diriger immédiatement vers {s=227} !\" répondit rapidement {u=tod}, \"Avec un peu de chance, nous atteindrons {s=227} à temps pour sauver vos amis.\""
tlks_meet_tod_2_4_q="\"Pourquoi vers {s=227} ?\""
tlks_meet_tod_2_4_a="\"S'ils vont dans cette direction, c'est qu'ils ont l'intention d'emmener vos amis dans leur repaire à {s=227}. L'endroit grouille de gobelins, mais la guilde n'a pas les moyens de tous les exterminer.\""
tlks_meet_tod_2_5_q="\"D'accord, en route pour {s=227} !\""

tlks_meet_thomas_1_a="Après le combat, l'homme qui semblait être un soldat, ou peut-être un garde, sortit de la pièce, \"Merci ! Ces monstres auraient sûrement défoncé la porte sans votre intervention.\""
tlks_meet_thomas_2_q="\"Nous appartenons à la guilde des aventuriers. Que s'est-il passé ?\""
tlks_meet_thomas_2_a="\"Je m'appelle {u=thomas}, et je suis l'un des gardes du banquier {u=brian}. Nous avons été pris dans une embuscade alors que nous étions en route pour {s=76}. Mon compagnon {u=william} et moi avons été piégés dans ce bâtiment par des monstres pendant notre retraite.\""
tlks_meet_thomas_3_q="\"Quel genre de monstres ?\""
tlks_meet_thomas_3_a="\"C'étaient des voleurs halfelins !\" répliqua amèrement {u=thomas}, \"Le plus étrange, c'était la présence de guerriers et d'archers squelettes.\""
tlks_meet_thomas_4_q="\"Pourquoi étrange ? Pour moi, ce sont tous des monstres.\""
tlks_meet_thomas_4_a="\"Les créatures mortes-vivantes, comme les squelettes et les zombis, ne sont pas rares, mais elles devraient rester au sein de leur misérable espèce. Je n'ai jamais vu auparavant des morts-vivants côtoyant des races civilisées.\" {u=thomas} secoue la tête en affichant un sourire amer, \"Je ne sais pas ce qui se passe dans notre monde.\""
tlks_meet_thomas_5_q="\"Alors, comme ça tu connais bien les morts-vivants ?\""
tlks_meet_thomas_5_a="\"Ha, ha ! Pas du tout !\", répond {u=thomas}, rejetant votre supposition, \"Pas comme tu le penses. En fait, mon oncle était clerc et il m'a appris quelques trucs sur eux quand j'étais plus jeune. Les tactiques de base, comme l'utilisation d'armes contondantes contre les squelettes. En tant que clerc, il possédait même la capacité de convertir les morts-vivants, bien qu'on ne puisse pas leur enseigner la foi.\""
tlks_meet_thomas_6_q="\"Où se trouve le banquier {u=brian} actuellement ?\""
tlks_meet_thomas_6_a="\"La majorité des gardes ont escorté {u=brian} pour le mettre en sécurité à {s=138}. Cependant, avec de si nombreux ennemis, j'ai un mauvais pressentiment.\""
tlks_meet_thomas_7_q="\"Nous avons été envoyés pour enquêter et vous protéger.\""
tlks_meet_thomas_7_a="\"Dieu soit loué ! Je commençais à perdre tout espoir. {u=william} a été gravement blessé et il faudrait l'évacuer le plus rapidement possible vers la ville la plus proche. Si vous me promettez de sauver {u=brian}, je pourrais enfin pousser un soupir de soulagement et emmener {u=william} en ville maintenant.\""
tlks_meet_thomas_8_q="\"Avant de partir, faites-nous part de toutes les informations que vous possédez. Elles pourraient nous être d'une grande utilité.\""
tlks_meet_thomas_8_a="\"Bien sûr. {s=138} est ici, sur la carte,\" répondit {u=thomas} en marquant l'endroit sur notre carte d'aventure. \"Je peux également vous laisser mon étoile du matin, juste au cas où vous rencontreriez des squelettes.\""
tlks_meet_thomas_9_q="\"Merci. Nous partons immédiatement au secours de votre patron !\""
tlks_meet_thomas_10_q="\"J'ai une autre question.\""
tlks_meet_thomas_10_a="\"D'accord.\""

tlks_banker_thank_1_1_a="\"Je vous remercie ! Je ne m'attendais plus à recevoir de l'aide.\" Après avoir raconté à {u=brian} ce qui s'est passé, il vous a exprimé toute sa gratitude."
tlks_banker_thank_1_2_q="\"Tu es le seul survivant de la troupe ?\""
tlks_banker_thank_1_2_a="\"Je n'en suis pas certain. Nous avons été séparés, car il y avait énormément d'ennemis. Plusieurs de mes gardes ont été tués et ensuite, j'ai été capturé par les assaillants.\""
tlks_banker_thank_1_3_q="\"Que pouvez-vous me dire sur vos assaillants ?\""
tlks_banker_thank_1_3_a="\"Je ne sais pas pourquoi ces halfelins nous ont attaqué, et je n'ai appris d'intéressant après qu'ils m'aient capturé, car ils parlaient dans leur propre langue.\""
tlks_banker_thank_1_4_q="\"Et sur ces squelettes ?\""
tlks_banker_thank_1_4_a="\"Ah oui, j'ai vu plusieurs de ces nabots commander des squelettes dans leur langue commune. Pendant qu'ils leur donnaient des ordres, ils tenaient entre leurs mains un étrange appareil. Un artefact magique d'où émanait une maléfique lueur violette.\""
tlks_banker_thank_1_5_q="\"Notre mission est de vous escorter jusqu'à {s=76}, où vous serez en sécurité. Allons_y.\""

tlks_banker_thank_2_1_a="\"Enfin, nous y voilà !\" dit {u=brian} en soufflant de soulagement, alors que nous arrivions aux portes de la ville, \"Je ne m'attendais pas à ce que ce voyage fut si long et si dangereux. Je vais devoir maintenant ouvrir la première banque sur le continent d'Alrthia. Je dois le rapatriement en toute sécurité de mes gardes à votre guilde des aventuriers, je vous remercie infiniment !\""
tlks_banker_thank_2_2_q="\"Quels services vont offrir votre banque ? Les aventuriers peuvent-ils y avoir recours ?\""
tlks_banker_thank_2_2_a="\"Bien sûr.\" {u=brian} se sentait ragaillardi rien que de parler de la banque, \"Les citoyens respectueux de la loi et les braves aventuriers ont le droit de bénéficier de nos services. Nos coffres-forts sont le moyen le plus sûr pour entreposer votre or.\""
tlks_banker_thank_2_3_q="\"Dans quelle ville comptez-vous ouvrir la première banque ?\""
tlks_banker_thank_2_3_a="\"C'est toujours à l'étude, car nous devons prendre en compte les résultats de toutes nos investigations. Si tout se passe pour le mieux, je pense que ça pourrait être l'une des plus grandes villes.\""
tlks_banker_thank_2_4_q="\"Combien de banques sont prévues sur le continent Alrthia ?\""
tlks_banker_thank_2_4_a="\"Plus il y en aura, et mieux ça sera !\" répondit {u=brian} avec un grand sourire, \"En fait, tout dépendra de plusieurs facteurs. Quelques grandes villes seront sélectionnées au début. Si nous obtenons de bons résultats, nous ouvrirons progressivement des agences dans d'autres villes.\""
tlks_banker_thank_2_5_q="\"Alors, n'en parlons pas pour le moment. Le travail nous attend et nous vous souhaitons bonne chance. Adieu.\""

qsts_1001_n="À la recherche des compagnons"
qsts_1001_d="Vous vous êtes réveillé(e) sur une étrange plage. Il s'avère qu'{u=aileen}, une membre de la guilde des aventuriers, vous a sauvé la vie, alors que vos compagnons, eux sont portés disparus.\n\nAvant de s'attaquer à d'autres problèmes en suspens, le plus urgent est de retrouver vos amis."
qsts_1001_1_n="Investigation le long du littoral"
qsts_1001_1_d="Des indices peuvent être trouvés en commençant vos recherches le long du littoral."
qsts_1001_1_msg="{ilu=beach_srch}En fouillant le littoral, vous ne tardez pas à découvrir des traces manifestes d'une lutte imprimées dans le sable de la plage. Vous apercevez une multitude d'empreintes de pas désordonnées, certaines de taille humaine, d'autres beaucoup plus petites.{p}Après une exploration de la zone plus approfondie, vous faites une nouvelle découverte : un sac à dos à moitié enterré sous le sable, ainsi que quelques potions éparpillées aux alentours. Ce sont les affaires de vos compagnons ! Vous suivez leurs traces afin de déterminer quelle direction ils ont prise. En avant !"
qsts_1001_2_n="Allons de l'avant"
qsts_1001_2_d="Les traces indiquent que vos compagnons ont probablement été emmenés par des monstres rôdant dans la région ! Vous devez les trouver avant qu'il ne soit trop tard."
qsts_1001_3_n="Le repaire des monstres"
qsts_1001_3_d="Vos compagnons ont été capturés par une bande de gobelins. Vous devez vous rendre dans leur repaire à {s=227} le plus vite possible !"
qsts_1001_3_obj_str="Secourir vos compagnons à {s=227}"
qsts_1001_3_msg="{ilu=spikes}{s=227}, comme son nom l'indique, est un bâtiment qui est facilement identifiable de très loin.\n\nToutefois, vous n'avez pas le temps de profiter du paysage. Vous repérez ces maudits gobelins à l'extérieur du bâtiment !{p}Ils se trémoussent autour d'une étrange statue se préparant à quelque chose, mais sans faire mine de vouloir rentrer dans la forteresse, laissant vos compagnons pratiquement sans surveillance.\n\nQuelle aubaine ! Vous consultez vos camarades d'un regard et d'un commun accord vous sortez vos armes..."
qsts_1001_3_msg2="{ilu=outpost}Le courage et la persévérance ont fini par porter leurs fruits. Vos compagnons ont été libérés avec seulement de légères blessures. Laissez-les récupérer dans une ville voisine et ils seront frais comme des gardons.{p}{u=aileen} vous suggère de vous diriger vers {s=26}.\n\n{s=26} est un avant-poste tenu par la guilde des aventuriers dans l'est du continent. {s=26} serait un endroit parfait pour se reposer et se ravitailler avant de repartir à l'aventure. En outre, {u=aileen} sera là pour les démarches administratives de votre inscription à la guilde des aventuriers.{p}Bien que vous et vos compagnons vous vous posiez beaucoup de questions, comme par exemple ce qui est arrivé à votre navire, vous n'avez plus le temps de penser à tout ça.\n\nVous êtes juste des aventuriers étrangers ont fait naufrage sur un continent étrange, et suivre les conseils d'{u=aileen} est sans doute votre meilleure et seule option pour le moment." 

qsts_1002_n="L'avant-poste"
qsts_1002_d="Suivant les conseils d'{u=aileen}, vous décidez de faire une halte à {s=26}. Pendant ce temps, {u=aileen} s'occupera des formalités administratives pour votre inscription à la guilde des aventuriers."

qsts_1003_n="Préparation indispensable"
qsts_1003_d="De bonnes compétences martiales et un équipement adapté sont indispensables pour un groupe d'aventuriers qualifiés, peu importe ce qui vous attend sur le terrain."

qsts_1004_n="Inscription des nouveaux membres"
qsts_1004_d="{u=aileen} a effectué les démarches nécessaires à votre place, et maintenant vous pouvez vous présenter à {s=63}, le quartier général de la guilde des aventuriers."

qsts_1005_n="Prouver votre valeur"
qsts_1005_d="Bienvenue à la guilde des aventuriers !\n\nNous avons reçu les rapports d'{u=aileen}, et nous vous remercions de votre visite. Comme vous le savez, un nombre anormalement élevé de monstres sillonne le continent, mutile et tue des innocents. Ces créatures doivent être éliminées le plus tôt possible.\n\nCependant, avant de vous confier des missions importantes, notre règlement nous impose d'envoyer de nouvelles équipes dans des opérations de routine afin de nous assurer qu'elles peuvent supporter les rigueurs de la vie d'aventurier.\n\nConseil :\nLa réputation d'un groupe d'aventuriers peut être améliorée en accomplissant des tâches en ville. Les pièces d'or peuvent être gagnées de bien des manières, telles que le commerce ou l'exploration de donjons."

qsts_1006_n="Partons à l'aventure"
qsts_1006_d="Bravo ! Vous avez apporté la preuve que vous êtes un groupe d'aventuriers compétents.\n\nMaintenant, vous pouvez entreprendre les quêtes assignées par la guilde."

qsts_1007_n="Le banquier porté disparu"
qsts_1007_d="Le célèbre banquier {u=brian}, qui a été invité récemment à rejoindre notre pays, n'est pas encore parvenu à sa destination, {s=76}. Il a déjà plusieurs jours de retard. Malgré son impressionnante escorte de gardes, nous pensons qu'il est préférable d'envoyer une équipe pour enquêter en raison de la récente recrudescence de monstres dans la région.\n\nLa meilleure zone pour commencer vos recherches a été marquée sur votre carte. Nous vous demandons d'y aller dès que possible. Votre mission sera d'escorter et de protéger {u=brian} jusqu'à {s=76}."
qsts_1007_1_n="À la recherche du banquier"
qsts_1007_1_d="Les informations concernant cette mission ne sont très clairs. De toute façon, nous devons nous diriger vers l'objectif marqué sur notre carte."
qsts_1007_1_msg="{ilu=broken_carriage}En arrivant à l'endroit indiqué, vous découvrez les restes d'une caravane : une carriole en piteux état et des approvisionnements éparpillés tout autour. Cependant, aucune trace du banquier ni de ses compagnons.{p}Après une inspection minutieuse de la zone, aucun indice intéressant n'a été découvert.\n\nIl ne vous reste plus qu'à élargir votre champ de recherches en vous rendant sur les autres sites suspects à proximité."
qsts_1007_2_n="Élargir le champ d'investigation"
qsts_1007_2_d="Le banquier et ses compagnons ont disparu. Vous décidez d'enquêter sur les zones suspectes à proximité."
qsts_1007_2_msg="{ilu=outdoor_monsters}Alors que vous approchez d'une petite chaumière, vous percevez un bruit de fond sourd.\n\nEn vous rapprochant plus près, vous apercevez plusieurs voleurs halfelins, en compagnie de deux squelettes, se tenant devant la cabane !{p}À votre approche, les monstres vous repèrent et vous attaquent !"
qsts_1007_2_false_dst_msg="<f=b7>Aucune trace du banquier et de ses compagnons.</f>"
qsts_1007_3_n="Le souffle de la mort"
qsts_1007_3_d="Vous avez reçu des informations plus détaillées, mais aussi plus inquiétantes, de l'une des escortes du banquier. Vous devez maintenant vous rendre la destination et sauver {u=brian}."
qsts_1007_3_msg="{ilu=breath_of_death}Avec les informations fournies par {u=thomas}, vous poursuivez vos recherches. Les traces d'un combat, ainsi que les corps des deux parties adverses, vous mènent progressivement à {s=138}.{p}En entrant dans le donjon, vous percevez une odeur nauséabonde de pourriture. Des fragments de squelette sont éparpillés sur le sol en pierre. Un mauvais pressentiment vous incite à partir sur le champ.{p}Cependant, certains indices indiquent que {u=brian} est probablement retenu à l'intérieur. Vous n'avez pas tellement le choix. D'après les conseils donnés par {u=thomas}, la meilleure tactique est de s'équiper des armes appropriées pour combattre la menace imminente des morts-vivants."
qsts_1007_4_n="Creuser en profondeur"
qsts_1007_4_d="Le banquier est probablement emprisonné dans {s=138} ! Prenez votre masse, fracassez tous les monstres, défoncez toutes les portes de cellule, et sauvez {u=brian} !"
qsts_1007_4_obj_str="Recherche et sauvetage du banquier"
qsts_1007_4_msg="{ilu=assassin_escape}Alors que vous vous apprêtez à nettoyer le champ de bataille et à secourir {u=brian}, une forte explosion retentit derrière vous, plongeant toute la pièce d'un épais brouillard de fumée...{p}Lorsque le gaz suffoquant se dissipe, vous réalisez avec stupéfaction que le corps du chef assassin a disparu !{p}Ensuite, vous fouillez minutieusement la pièce et les alentours pour ne trouver que le butin laissé par l'ennemi et une lettre, sans aucun intérêt.{p}Cependant, la plus grande victoire est d'avoir sauvé un innocent ! En outre, il pourrait savoir quelque chose."

qsts_1007_5_n="L'escorte"
qsts_1007_5_d="Malgré cette première victoire, il ne fait aucun doute que d'autres auront besoin de notre aide. Nous ne pouvons pas nous permettre de nous laisser distraire. Avec cette menace inconnue dissimulée dans les ombres, nous devons escorter {u=brian} à {s=76} le plus rapidement possible."

qsts_1008_n="Serrurier à temps partiel"
qsts_1008_d="Vous avez plusieurs coffres sans propriétaire dans la guilde. Si vous parvenez à les ouvrir en toute sécurité, les objets à l'intérieur seront à vous.\n\nLaissez-y un ou deux membres de votre groupe pour l'apprendre. Ça pourrait vous être utile lors de vos aventures futures.\n\nEn outre, pensez à acheter quelques outils de crochetage en cours de route."

qsts_1009_n="De meilleurs outils"
qsts_1009_d="L'utilisation des compétence crochetage et désarmorçage nécessite divers outils.\n\nBien que de simples outils puissent puissent faire l'affaire, ils sont essentiellement destinés aux débutants. Pour les professionnels, un ensemble d'outils de voleur décents et même une version plus sophistiquée sont indispensables."

qsts_1010_n="La compétence indispensable"
qsts_1010_d="Pour les aventuriers, le désarmorçage d'un dispositif peut être une question de vie ou de mort. Il n'est certainement pas prudent de se précipiter dans un donjon plein de pièges sans avoir appris au préalable cette compétence.\n\nIl est recommandé d'y laisser plusiers membres de votre groupe ayant la plus grande intelligence pour apprendre cette compétence."

qsts_1011_n="La détresse des artisans"
qsts_1011_d="La guilde des artisans rencontre de sérieux problèmes et elle a demandé l'aide de la guilde des aventuriers. Votre groupe a été envoyé pour leur venir en aide."
qsts_1011_1_n="Une situation d'urgence"
qsts_1011_1_d="Rendez vous à la guilde des artisans dès que possible !"
qsts_1011_2_n="Rétablissement de l'approvisionnement en ressources"
qsts_1011_2_d="Pour le moment, le plus gros problème des artisans est l'occupation par des monstres de nombreux sites de production de matières premières, ce qui a entraîné une pénurie de ressources. Veuillez rendre accessible quelques sites le plus rapidement possible afin de répondre aux besoins les plus urgents."
qsts_1011_3_n="Continuer d'aider les artisans"
qsts_1011_3_d="Les sites de ressources ont été reconquis avec succès ! Mais la pénurie de matières premières était trop importante. La guilde des artisans vous demande de l'aider à collecter les matières premières dont elle a un besoin urgent.\n\nLa guilde des artisans fournit des services de formation pour des compétences artisanales."
qsts_1011_4_n="La collecte de ressources"
qsts_1011_4_d="De manière générale, différents types de matières premières doivent être collectés sur différents sites de ressources. Mais parfois, une petite quantité d'autres matières premières peut être trouvée dans certains sites."

qsts_1012_n="Artisan expert"
qsts_1012_d="Pour les aventuriers ordinaires, bien que l'équipement commun puisse être trouvé partout, un équipement de haute qualité n'est pas facile à obtenir\n\nLa Guilde des Artisans peut vous aider à résoudre ce problème et a décidé d'améliorer vos connaissances pour que vous puissiez fabriquer un équipement plus efficace."
qsts_1012_1_n="Acier et Feu"
qsts_1012_1_d="Un équipement de qualité demande du matériel de qualité ! Transformer du matériel est un art qui demande beaucoup de pratique pour devenir un artisan qualifié."
qsts_1012_2_n="Maître Artisan"
qsts_1012_2_d="Fournissent des équipements de haute qualité et les livrent à la Guilde des Aventuriers."

-- z_add_qst.2