g_end_talk="(Encerrar conversa)"
g_story_start_full_scrn_text="Você abre os olhos lentamente, a tontura ainda turva sua mente..."
g_banker_boss_pre_msg="{ilu=tied_in_room}Você se aproxima furtivamente da porta, mas ainda luta para entender a voz que fala dentro da sala além. {p}Felizmente, uma fenda na velha porta de carvalho permite que você dê uma espiada. \n\nApenas alguns inimigos ocupam a sala, incluindo seu líder, que se ergue ameaçador no canto resmungando ordens. {p}Do outro lado da sala, um homem está pendurado em um pilar, cordas de couro cru cravando-se cruelmente em seus pulsos amarrados. Você pensa consigo mesmo, este pode ser o banqueiro {u=brian}. \n\nO que você vai fazer agora?"

tlks_meet_aileen_1_a="Uma jovem mulher senta-se ao seu lado, olhando para baixo com preocupação estampada em seu rosto. \"Deus a abençoe, você finalmente acordou! Como você se sente? Lembra o que aconteceu? \""
tlks_meet_aileen_2_q="\"Hmm..... Estou tonto. Quem é você? Você me salvou?\""
tlks_meet_aileen_2_a="\"Eu sou {u=aileen}. Encontramos você desmaiado na praia. Você é um aventureiro, não é? Mas não deste lugar...\" A senhora te observa e pergunta, \"Você está aqui sozinho ou estava com companheiros?\""
tlks_meet_aileen_3_q="\"Nós?\""
tlks_meet_aileen_3_a="\"Ah, desculpe, esqueci de te contar.\" A senhora continuou, \"Meu companheiro {u=tod} e eu somos da Guilda dos Aventureiros, recebemos aventureiros do continente oriental. Talvez sua memória ainda não tenha se recuperado? Tudo isso deveria ter sido explicado na sua carta de convite.\""
tlks_meet_aileen_4_q="\"Que lugar é este?\""
tlks_meet_aileen_4_a="\"Esta é a praia mais próxima de {s=41}. {s=41} não fica longe daqui. Foi aqui que você deveria ter desembarcado. Vamos deixar outras perguntas de lado por enquanto, tarefas importantes nos aguardam.\""
tlks_meet_aileen_5_q="\"Vim com vários aventureiros. Vocês os viram?\""
tlks_meet_aileen_5_a="\"Nós apenas o encontramos. Meu companheiro {u=tod} tem procurado os outros, mas ainda não encontrou pistas de onde eles podem estar. Precisamos nos apressar para encontrá-los, pois muitos monstros vagueiam por esta faixa da costa.\" {u=aileen} explica ansiosamente, \"É melhor nos prepararmos para uma luta caso queira salvar seus companheiros. Está pronto?\""
tlks_meet_aileen_6_q="\"Sim, vamos imediatamente. Não quero arriscar perder nenhum dos meus amigos.\""
tlks_meet_aileen_7_q="\"Há algo mais que devo descobrir.\""
tlks_meet_aileen_7_a="\"Tudo bem, mas não temos tempo a perder.\""

tlks_meet_tod_1_a="\"{u=aileen}! Goblin!\" Um jovem combatente corre em sua direção com dois goblins atrás dele. Lanças voam sobre seus ombros e cravam-se no chão bem à sua frente."
tlks_meet_tod_2_q="Empunhe suas armas!"
tlks_meet_tod_3_q="\"O quê? Quem é você?\""
tlks_meet_tod_3_a="\"Corta essa baboseira, novato! Você pega o pequeno!\" O homem revira os olhos."

tlks_meet_tod_2_1_a="\"Esses malditos goblins!\" O jovem combatente deve ser o companheiro {u=tod} que {u=aileen} mencionou. Depois de amaldiçoar as pequenas bestas repugnantes, {u=tod} relata os resultados de sua busca, \"Seus companheiros foram levados por uma banda de goblins. Infelizmente, a maioria deles abandonou o acampamento quando eu segui o rastro. Matei dois, não, três deles. O resto, sem dúvida, está com seus amigos.\""
tlks_meet_tod_2_2_q="\"Como estão meus companheiros? Eles estão feridos??\""
tlks_meet_tod_2_2_a="\"Desculpe, não consegui vê-los claramente de tão longe. Eles ainda estavam de pé, porém, então duvido que estejam gravemente feridos.\""
tlks_meet_tod_2_3_q="\"O que faremos agora?\""
tlks_meet_tod_2_3_a="\"Devemos nos mover em direção a {s=227} imediatamente!\" {u=tod} diz apressadamente, \"Se tivermos sorte, chegaremos a {s=227} a tempo de salvar seus companheiros.\""
tlks_meet_tod_2_4_q="\"Por que {s=227}?\""
tlks_meet_tod_2_4_a="\"Se eles estão indo nessa direção, só podem estar levando seus amigos para sua caverna {s=227}. O local está infestado de goblins, mas a guilda não tem mão de obra suficiente para matá-los todos.\""
tlks_meet_tod_2_5_q="\"OK, vamos para {s=227}!\""

tlks_meet_thomas_1_a="Depois da batalha, o homem que parece um soldado ou talvez um guarda sai da sala, \"Obrigado! Esses monstros certamente teriam arrombado a porta sem sua ajuda.\""
tlks_meet_thomas_2_q="\"Somos aventureiros da Guilda dos Aventureiros. O que aconteceu?\""
tlks_meet_thomas_2_a="\"Eu sou {u=thomas}, um dos {u=brian} guardas do banqueiro. Fomos emboscados a caminho de {s=76}. Meu companheiro, {u=william}, e eu ficamos presos no prédio pelos monstros durante a evacuação.\""
tlks_meet_thomas_3_q="\"Quem são esses monstros?\""
tlks_meet_thomas_3_a="\"São ladrões halfling!\" {u=thomas} responde amargamente, \"É estranho ver guerreiros esqueletos e arqueiros esqueletos presentes.\""
tlks_meet_thomas_4_q="\"Por que estranho? Eu os considerava monstros comuns.\""
tlks_meet_thomas_4_a="\"Criaturas mortas-vivas fracas como esqueletos e zumbis não são raras, mas deveriam estar entre seu próprio tipo miserável. Nunca vi tais demônios mortos-vivos trabalhar ao lado das raças civilizadas antes.\" {u=thomas} balança a cabeça exibindo um sorriso amargo, \"Não sei o que está acontecendo neste mundo.\""
tlks_meet_thomas_5_q="\"Então você conhece os mortos-vivos?\""
tlks_meet_thomas_5_a="\"Haha! Não sou especialista.\", {u=thomas} responde, \"Na verdade, meu tio era clérigo e me ensinou algumas coisas sobre eles quando eu era menino. Táticas básicas como usar armas contundentes contra esqueletos. Como clérigo, ele até possuía a habilidade de afastar os mortos-vivos, embora não se possa ensinar fé.\""
tlks_meet_thomas_6_q="\"Onde está o banqueiro, {u=brian}, agora?\""
tlks_meet_thomas_6_a="\"A maioria dos guardas escoltou {u=brian} durante a evacuação em direção a {s=138}. No entanto, com tantos inimigos por perto, tenho um mau pressentimento.\""
tlks_meet_thomas_7_q="\"Fomos enviados para investigar o que aconteceu e oferecer proteção.\""
tlks_meet_thomas_7_a="\"Graças a Deus! Eu estava indefeso há pouco, {u=william} ficou gravemente ferido e deve ser levado imediatamente à cidade mais próxima. Como vocês buscam resgatar {u=brian}, finalmente posso respirar aliviado e enviar {u=william} para a cidade agora.\""
tlks_meet_thomas_8_q="\"Forneça-nos todas as informações que você tem. Por favor, isso seria de grande ajuda.\""
tlks_meet_thomas_8_a="\"Com certeza. {s=138} está aqui no mapa,\" {u=thomas} diz ao marcar a localização no nosso mapa de aventura. \"Além disso, tenho uma maça de haste para você, caso encontre esqueletos.\""
tlks_meet_thomas_9_q="\"Obrigado. Partiremos para o resgate imediatamente!\""
tlks_meet_thomas_10_q="\"Tenho outra pergunta.\""
tlks_meet_thomas_10_a="\"OK.\""

tlks_banker_thank_1_1_a="\"Obrigado! Nunca esperei que a ajuda chegasse.\" Ao relatar o que aconteceu a {u=brian}, ele expressa solenemente sua gratidão."
tlks_banker_thank_1_2_q="\"Só você sobreviveu na sua tropa?\""
tlks_banker_thank_1_2_a="\"Não tenho certeza. Fomos separados e havia tantos inimigos. Vários dos meus guardas foram mortos e, depois, fui capturado pelos agressores.\""
tlks_banker_thank_1_3_q="\"Você sabe algo sobre esses agressores?\""
tlks_banker_thank_1_3_a="\"Não sei por que aqueles halflings atacariam minhas tropas. Não ouvi nada útil quando fui capturado, pois eles só falavam em sua própria língua.\""
tlks_banker_thank_1_4_q="\"Algo sobre esses esqueletos?\""
tlks_banker_thank_1_4_a="\"Ah, eu vi vários daqueles gnomos comandando alguns esqueletos em língua comum. Eles seguravam um dispositivo estranho enquanto faziam isso. Um artefato mágico que brilhava em um tom maligno de violeta.\""
tlks_banker_thank_1_5_q="\"Nossa missão é escoltá-lo(a) com segurança até {s=76}, vamos.\""

tlks_banker_thank_2_1_a="\"Finalmente, aqui estamos!\" {u=brian} respira fundo ao chegar ao portão, \"Não esperava que esta {s=76} viagem fosse tão longa e perigosa. Devo me preparar para abrir o primeiro banco no continente de Alrthia. Devo a segurança dos meus guardas à sua Guilda dos Aventureiros, muito obrigado!\""
tlks_banker_thank_2_2_q="\"Quais serviços o banco oferece? Aventureiros podem usá-lo?\""
tlks_banker_thank_2_2_a="\"Com certeza.\" {u=brian} parece animado ao falar sobre o banco. \"Tanto cidadãos cumpridores da lei quanto bravos aventureiros têm direito a usufruir de nossos serviços. Nossos cofres de depósito são a forma mais segura de guardar seu ouro.\""
tlks_banker_thank_2_3_q="\"Qual cidade você tem em mente para o primeiro banco?\""
tlks_banker_thank_2_3_a="\"Ainda está em aberto, devemos considerar os resultados finais da investigação. Acho que pode ser uma das maiores cidades, se nada der errado.\""
tlks_banker_thank_2_4_q="\"Quantos bancos estão planejados para serem abertos no continente de Alrthia?\""
tlks_banker_thank_2_4_a="\"Quanto mais, melhor!\" {u=brian} diz com um sorriso, \"Na verdade, depende. Algumas grandes cidades serão selecionadas para operação na fase inicial. Se tivermos um bom desempenho, expandiremos gradualmente para mais cidades.\""
tlks_banker_thank_2_5_q="\"Não há de quê, é nosso trabalho. Boa sorte e adeus.\""

qsts_1001_n="Procurando Companheiros"
qsts_1001_d="Você acorda em uma praia estranha. Acontece que a Lady {u=aileen}, membro da Guilda dos Aventureiros, salvou você enquanto seus companheiros estavam desaparecidos.\n\nMuitos problemas ainda precisam ser resolvidos, o mais urgente é encontrar seus companheiros."
qsts_1001_1_n="Vasculhando a Costa"
qsts_1001_1_d="Pistas podem ser encontradas ao percorrer a costa em sua busca."
qsts_1001_1_msg="{ilu=beach_srch}Ao vasculhar a costa, você logo encontra sinais óbvios de luta escritos nas areias da praia. Vê um conjunto de pegadas desordenadas, algumas do tamanho de humanos, mas a maioria menores.{p}Felizmente, após mais exploração, faz uma descoberta: uma mochila enterrada na areia e algumas poções espalhadas, pertences de seus companheiros! Você usa as trilhas para determinar a direção que seguiram. Em frente!"
qsts_1001_2_n="Seguindo em Frente"
qsts_1001_2_d="As pistas indicam que seus companheiros provavelmente foram levados por monstros que espreitam a região! Você deve encontrá-los antes que seja tarde demais."
qsts_1001_3_n="Covil do Monstro"
qsts_1001_3_d="Seus companheiros foram levados por uma banda de goblins. Você deve ir ao covil deles {s=227} o mais rápido possível!"
qsts_1001_3_obj_str="Resgate seus companheiros em {s=227}"
qsts_1001_3_msg="{ilu=spikes}{s=227}, como o nome indica, pode ser facilmente identificado mesmo a uma distância tão grande como esta.\n\nNo entanto, não há tempo para apreciar a paisagem. Você encontra aqueles malditos goblins fora do edifício!{p}Eles circulam ao redor de uma estátua estranha preparando algo sem entrar na fortaleza, deixando seus companheiros praticamente desprotegidos.\n\nEsta é a nossa chance! Com um aceno, vocês se encaram e sacam suas armas......."
qsts_1001_3_msg2="{ilu=outpost}Coragem e persistência finalmente dão frutos. Seus companheiros são resgatados com baixas mínimas. Deixe-os se recuperar nas cidades próximas e estarão como novos.{p}{u=aileen} sugere que você siga para {s=26}.\n\n{s=26} é um posto avançado mantido pela Guilda dos Aventureiros no continente oriental. {s=26} é um local ideal para descansar e reabastecer os grupos de aventureiros. {u=aileen} cuidará de registrá-lo na Guilda dos Aventureiros para que você possa dar seguimento a eles.{p}Embora você e seus companheiros tenham muitas perguntas, como o que aconteceu com sua embarcação, não há tempo para se deter sobre elas.\n\nAventureiros estrangeiros naufragados em um continente estranho descobrirão que seguir o conselho de {u=aileen} é, sem dúvida, a melhor e única opção neste exato momento." 

qsts_1002_n="Posto Avançado"
qsts_1002_d="De acordo com {u=aileen}, você decide fazer uma pausa em {s=26}. Enquanto isso, {u=aileen} cuidará dos trâmites para registrá-lo na Guilda dos Aventureiros para acompanhamento."

qsts_1003_n="Preparação Necessária"
qsts_1003_d="Proeza de combate suficiente e suprimentos adequados são essenciais para um grupo de aventureiros qualificado, não importa o que esteja à sua frente."

qsts_1004_n="Registro de Novato"
qsts_1004_d="{u=aileen} preparou os procedimentos necessários para você, e agora você pode se apresentar para o serviço em {s=63}, a sede da Guilda dos Aventureiros."

qsts_1005_n="Comprovando Sua Força"
qsts_1005_d="Bem-vindo à Guilda dos Aventureiros!\n\nJá recebemos o relatório de {u=aileen}, muito obrigado por resolver esta crise! Como você sabe, um número anormalmente grande de monstros persegue o continente, mutilando e matando inocentes. Essas bestas devem ser erradicadas com a máxima urgência.\n\nNo entanto, antes de atribuir missões importantes, nossas regras exigem que enviemos grupos em missões rotineiras para testar sua coragem. Isso garante que eles possam lidar com as exigências da vida de aventureiro.\n\nDica:\nO valor de reputação do grupo de aventureiros pode ser aumentado completando tarefas nas cidades, enquanto moedas de ouro podem ser ganhas de várias formas, como comércio ou exploração de masmorras, etc."

qsts_1006_n="Embarque em Aventuras"
qsts_1006_d="Bem feito! Você provou ser um grupo de aventureiros qualificado.\n\nAgora a guilda tem algumas outras missões tutorial para ajudá-lo a aprender mais sobre as habilidades que os aventureiros precisam. Conforme seu grupo cresce, você receberá mais missões da guilda no futuro.\n\nClaro, não há pressa para concluir essas missões. O mais importante, agora você pode embarcar em aventuras e desenvolver seu grupo livremente!\n\n<c=o>(Este jogo está atualmente em fase de Acesso Antecipado e mais conteúdo será adicionado continuamente! Obrigado novamente pelo seu apoio.\n\n-- Low Magic Studios)</c>"

qsts_1007_n="O Banqueiro Desaparecido"
qsts_1007_d="Um banqueiro bem conhecido chamado {u=brian} foi recentemente convidado para nossa terra. Ele ainda não chegou ao seu destino em {s=76}, mas está com vários dias de atraso. Flores viajava com uma formidável escolta de guardas, mas devido à recente atividade de monstros consideramos necessário enviar alguém para investigar seu atraso.\n\nO melhor ponto de partida para sua busca foi marcado no mapa. Por favor, dirija-se lá o mais rápido possível. Sua missão é escoltar {u=brian} de volta a {s=76} em segurança."
qsts_1007_1_n="Procurando o Banqueiro"
qsts_1007_1_d="Os detalhes da situação não estão claros, porém, você deve seguir para o local alvo o mais rápido possível."
qsts_1007_1_msg="{ilu=broken_carriage}Ao chegar ao local designado, você encontra as ruínas de uma caravana. Vê uma carroça quebrada e suprimentos espalhados. No entanto, não há sinal do banqueiro ou de seus companheiros.{p}Após uma busca adicional na área, nenhum indício valioso foi encontrado.\n\nAgora você só pode ampliar o escopo da sua busca investigando outros locais suspeitos nas proximidades."
qsts_1007_2_n="Ampliando o Escopo"
qsts_1007_2_d="O banqueiro e seus companheiros estão desaparecidos, você decide investigar lugares suspeitos nas proximidades."
qsts_1007_2_msg="{ilu=outdoor_monsters}Ao se aproximar da cabana selvagem, você pode ouvir o zumbido de atividade.\n\nAo chegar mais perto, você avista vários ladrões halflings e dois esqueletos em frente à cabana!{p}Nesse mesmo momento, os monstros o avistam e atacam!"
qsts_1007_2_false_dst_msg="<f=b7>Nenhum vestígio do banqueiro ou de seus companheiros.</f>"
qsts_1007_3_n="O Sopro da Morte"
qsts_1007_3_d="Você recebe notícias mais informativas, porém também mais preocupantes, de um dos escoltas do banqueiro. Agora você deve ir ao destino e resgatar {u=brian}."
qsts_1007_3_msg="{ilu=breath_of_death}Com as informações obtidas de {u=thomas}, você continua a busca. Os sinais de luta, bem como os restos não enterrados dos combatentes, gradualmente o conduzem a {s=138}.{p}Ao entrar na masmorra, você detecta o fétido odor de podridão e vê fragmentos esqueléticos espalhados por todo o chão de pedra. Uma sensação ominosa o obriga a sair imediatamente.{p}No entanto, todos os indícios parecem indicar que {u=brian} está provavelmente sendo mantido dentro. Você não tem muitas opções neste ponto. Segundo o conselho de {u=thomas}, a melhor ação é preparar as armas adequadas ou meios para combater a ameaça dos mortos-vivos que se aproxima."
qsts_1007_4_n="Cavando Fundo"
qsts_1007_4_d="O banqueiro provavelmente está aprisionado em {s=138}! Pegue seu martelo, esmague cada monstro, arrebente todas as portas das celas e salve {u=brian}!"
qsts_1007_4_obj_str="Procurando e resgatando o banqueiro"
qsts_1007_4_msg="{ilu=assassin_escape}Enquanto você se prepara para limpar o campo de batalha e resgatar {u=brian}, uma forte explosão estronda atrás de você, deixando toda a sala envolta em uma densa fumaça.....{p}Quando o gás sufocante se dissipa, você percebe, chocado, que o corpo do líder assassino desapareceu!{p}Depois, você revê tanto a sala quanto as áreas ao redor minuciosamente. Encontra alguns saque deixado pelo inimigo, bem como uma carta, mas nenhuma outra informação útil.{p}No entanto, o resgate bem-sucedido de um inocente é uma grande vitória! Além disso, ele pode saber algo."

qsts_1007_5_n="Escolta"
qsts_1007_5_d="Apesar desta vitória, não há dúvida de que há outros que precisam de ajuda. Não podemos nos distrair. Com uma ameaça desconhecida espreitando na escuridão, devemos escoltar {u=brian} para {s=76} o mais rápido possível."

qsts_1008_n="Chaveiro Meio-Período"
qsts_1008_d="Você recebeu vários baús sem dono da guilda. Se puder abri-los com segurança, os itens dentro serão seus.\n\nFaça um ou dois membros do grupo treinarem para aprender a perícia de abrir fechadura. Isso será útil para suas futuras aventuras.\n\nAlém disso, você precisará comprar alguns gazuas ao longo do caminho."

qsts_1009_n="Ferramentas Melhores"
qsts_1009_d="Usar as perícias de Desativar Dispositivo e Abrir Fechadura requer várias ferramentas.\n\nEmbora o conjunto de ferramentas simples seja apenas utilizável, ele serve basicamente para iniciantes. Para profissionais, um conjunto decente de ferramentas de ladrão ou até mesmo um conjunto de ferramentas de obra-prima são indispensáveis."

qsts_1010_n="A Perícia Essencial"
qsts_1010_d="Para aventureiros, a perícia de Desativar Dispositivo pode ser uma habilidade crucial de vida ou morte para a exploração de masmorras. Definitivamente não é sensato entrar apressado em uma masmorra cheia de armadilhas sem aprender essa perícia.\n\nRecomenda-se que vários membros do grupo com alta Inteligência aprendam essa perícia."

qsts_1011_n="A Situação dos Artesãos"
qsts_1011_d="A Guilda dos Artesãos próxima enfrentou sérios contratempos e está pedindo ajuda à Guilda dos Aventureiros. Seu grupo está sendo enviado para auxiliá-los."
qsts_1011_1_n="Situação Urgente"
qsts_1011_1_d="Vá ao local da Guilda dos Artesãos o mais rápido possível!"
qsts_1011_2_n="Restabelecimento do Suprimento de Recursos"
qsts_1011_2_d="Atualmente, o maior problema que os artesãos enfrentam é a grave escassez de matérias-primas. Isso ocorre porque os locais de recursos estão ocupados por monstros. Por favor, recupere alguns desses locais o mais rápido possível para atender a essa necessidade urgente."
qsts_1011_3_n="Ajude os outros até o fim"
qsts_1011_3_d="Os locais de recursos foram reconquistados com sucesso, mas a lacuna no suprimento de matérias-primas é enorme. A Guilda dos Artesãos pede que você ajude a coletar algumas matérias-primas urgentemente necessárias. \n\nA Guilda dos Artesãos oferece serviços de treinamento para habilidades relacionadas."
qsts_1011_4_n="Coleta de Recursos"
qsts_1011_4_d="De modo geral, diferentes tipos de matérias-primas precisam ser coletados em vários locais de recursos. Contudo, às vezes, pequenas quantidades de outros tipos de matérias-primas também podem ser encontradas nesses locais."

qsts_1012_n="Artesão Habilidoso"
qsts_1012_d="Embora aventureiros comuns possam encontrar equipamentos básicos praticamente em qualquer lugar, equipamentos mais adequados ou de alta qualidade não são tão fáceis de obter.\n\nDepois de ajudar com sucesso a Guilda dos Artesãos a resolver uma série de problemas, a Guilda dos Aventureiros decidiu permitir que você aprenda várias habilidades de fabricação de equipamentos com a Guilda dos Artesãos para ajudar a resolver a escassez de equipamentos dos novos aventureiros."
qsts_1012_1_n="Aço e Fogo"
qsts_1012_1_d="Equipamento de qualidade vem de materiais de qualidade! Familiarizar-se com o artesanato de diversos materiais é um curso obrigatório para se tornar um artesão qualificado."
qsts_1012_2_n="Espírito do Artesão"
qsts_1012_2_d="Forje um lote de equipamentos de alta qualidade e entregue-o à Guilda dos Aventureiros."

-- z_add_qst.2