g_end_talk="(Fim da conversa)"
g_story_start_full_scrn_text="Você abre lentamente os olhos, ainda sentindo tontura que turva sua mente..."
g_banker_boss_pre_msg="{ilu=tied_in_room}Você se aproxima furtivamente da porta, mas ainda luta para entender a voz que fala dentro da sala além. {p}Felizmente, uma fresta na velha porta de carvalho permite que você espreite para dentro. \n\nApenas alguns inimigos ocupam a sala, incluindo seu líder, que se destaca no canto, resmungando ordens. {p}Do outro lado da sala, um homem está pendurado em um pilar, cordas de couro cru cruelmente cravadas em seus pulsos amarrados. Você pensa consigo mesmo, este pode ser o banqueiro {u=brian}. \n\nO que você vai fazer agora?"

tlks_meet_aileen_1_a="Uma jovem mulher senta-se ao seu lado, olhando para baixo com preocupação estampada no rosto. \"Deus a abençoe, você finalmente acordou! Como você está se sentindo? Lembra-se do que aconteceu? \""
tlks_meet_aileen_2_q="\"Hmm..... Estou tonto. Quem é você? Você me salvou?\""
tlks_meet_aileen_2_a="\"Eu sou {u=aileen}. Nós te encontramos desmaiado na praia. Você é uma aventureira, não é? Mas não é desta terra...\" A senhora te observa e pergunta, \"Você está aqui sozinho ou veio com companheiros?\""
tlks_meet_aileen_3_q="\"Nós?\""
tlks_meet_aileen_3_a="\"Ah, desculpe, eu esqueci de te contar.\" A senhora continuou, \"Meu companheiro {u=tod} e eu somos ambos da Guilda de Aventureiros, nós acolhemos aventureiros do continente oriental. Talvez sua memória ainda não tenha se recuperado? Tudo isso deveria ter sido explicado na sua carta de convite.\""
tlks_meet_aileen_4_q="\"Onde nós estamos?\""
tlks_meet_aileen_4_a="\"Esta é a praia mais próxima de {s=41}. {s=41} não fica longe daqui. É lá que você deveria ter desembarcado. Vamos deixar as perguntas de lado por enquanto, tarefas importantes estão à nossa frente.\""
tlks_meet_aileen_5_q="\"Eu vim com vários aventureiros. Você os viu?\""
tlks_meet_aileen_5_a="\"Nós só encontramos você. Meu companheiro {u=tod} tem procurado por outros, mas até agora não encontrou pistas de onde eles possam estar. Devemos nos apressar para rastreá-los, pois muitos monstros vagueiam por esta faixa da costa.\" {u=aileen} explica ansiosamente, \"É melhor nos prepararmos para uma luta caso você queira salvar seus companheiros. Você está pronto?\""
tlks_meet_aileen_6_q="\"Sim, vamos partir agora mesmo. Não quero arriscar perder nenhum de meus amigos.\""
tlks_meet_aileen_7_q="\"Há algo mais que eu devo descobrir.\""
tlks_meet_aileen_7_a="\"Tudo bem, mas não temos tempo a perder.\""

tlks_meet_tod_1_a="\"{u=aileen}! Goblin!\" Um jovem guerreiro corre em sua direção com dois goblins seguindo atrás. Lanças voam por cima de seus ombros e se cravam no chão bem na sua frente."
tlks_meet_tod_2_q="Pegue suas armas!"
tlks_meet_tod_3_q="\"O quê? Quem é você?\""
tlks_meet_tod_3_a="\"Pare com essa conversa fiada, novato! Você pega o pequeno!\" O homem revira os olhos."

tlks_meet_tod_2_1_a="\"Esses malditos goblins!\" O jovem guerreiro deve ser o companheiro {u=tod} que {u=aileen} mencionou. Depois de xingar as pequenas bestas, {u=tod} relata os resultados de sua busca, \"Seus companheiros foram levados por uma matilha de goblins. Infelizmente, a maior parte deles já havia partido quando eu peguei o rastro. Matei dois, não, três deles. Os outros sem dúvida estão com seus amigos.\""
tlks_meet_tod_2_2_q="\"Como estão meus companheiros? Eles estão feridos?\""
tlks_meet_tod_2_2_a="\"Desculpe, não consegui vê-los claramente de tão longe. Eles ainda estavam de pé, então duvido que algum esteja gravemente ferido.\""
tlks_meet_tod_2_3_q="\"O que faremos agora?\""
tlks_meet_tod_2_3_a="\"Devemos nos dirigir imediatamente para {s=227}!\" {u=tod} diz apressadamente, \"Se tivermos sorte chegaremos a {s=227} a tempo de salvar seus companheiros.\""
tlks_meet_tod_2_4_q="\"Por que {s=227}?\""
tlks_meet_tod_2_4_a="\"Se eles estão indo naquela direção, só podem estar levando seus amigos para o covil deles em {s=227}. O lugar está cheio de goblins, mas a guilda não pode dispensar mão de obra para matá-los todos.\""
tlks_meet_tod_2_5_q="\"OK, vamos para {s=227}!\""

tlks_meet_thomas_1_a="Após a batalha, o homem que parece ser um soldado ou talvez um guarda sai da sala, \"Obrigado! Esses monstros certamente teriam arrombado a porta sem a sua ajuda.\""
tlks_meet_thomas_2_q="\"Nós somos aventureiros da Guilda de Aventureiros. O que aconteceu?\""
tlks_meet_thomas_2_a="\"Eu sou {u=thomas}, um dos guardas do banqueiro {u=brian}. Fomos emboscados a caminho de {s=76}. Meu companheiro, {u=william}, e eu fomos presos no prédio por monstros durante a evacuação.\""
tlks_meet_thomas_3_q="\"Quem são esses monstros?\""
tlks_meet_thomas_3_a="\"Eles são ladrões halflings!\" {u=thomas} responde amargamente, \"É estranho ver guerreiros esqueléticos e arqueiros esqueléticos presentes.\""
tlks_meet_thomas_4_q="\"Por que estranho? Eu pensei que fossem monstros comuns.\""
tlks_meet_thomas_4_a="\"Criaturas não-mortas fracas como esqueletos e zumbis não são raras, mas elas deveriam estar entre sua própria espécie miserável. Nunca vi esses demônios não-mortos trabalhando ao lado de raças civilizadas antes.\" {u=thomas} balança a cabeça exibindo um sorriso amargo, \"Não sei o que está acontecendo com este mundo.\""
tlks_meet_thomas_5_q="\"Então você conhece sobre os não-mortos?\""
tlks_meet_thomas_5_a="\"Haha! Eu não sou nenhum expert.\", {u=thomas} responde, \"Na verdade, meu tio era um clérigo e me ensinou algumas coisas sobre eles quando eu era menino. Táticas básicas como usar armas contundentes contra esqueletos. Como clérigo, ele até possuía a habilidade de banir os não-mortos, embora você não possa ensinar fé.\""
