g_end_talk="(Fim da conversa)"
g_story_start_full_scrn_text="Você abre lentamente os olhos, ainda sentindo tontura que turva sua mente..."
g_banker_boss_pre_msg="{ilu=tied_in_room}Você se aproxima furtivamente da porta, mas ainda luta para entender a voz que fala dentro da sala além. {p}Felizmente, uma fresta na velha porta de carvalho permite que você espreite para dentro. \n\nApenas alguns inimigos ocupam a sala, incluindo seu líder, que se destaca no canto, resmungando ordens. {p}Do outro lado da sala, um homem está pendurado em um pilar, cordas de couro cru cruelmente cravadas em seus pulsos amarrados. Você pensa consigo mesmo, este pode ser o banqueiro {u=brian}. \n\nO que você vai fazer agora?"

tlks_meet_aileen_1_a="Uma jovem mulher senta-se ao seu lado, olhando para baixo com preocupação estampada no rosto. \"Deus a abençoe, você finalmente acordou! Como você está se sentindo? Lembra-se do que aconteceu? \""
tlks_meet_aileen_2_q="\"Hmm..... Estou tonto. Quem é você? Você me salvou?\""
tlks_meet_aileen_2_a="\"Eu sou {u=aileen}. Nós te encontramos desmaiado na praia. Você é uma aventureira, não é? Mas não é desta terra...\" A senhora te observa e pergunta, \"Você está aqui sozinho ou veio com companheiros?\""
tlks_meet_aileen_3_q="\"Nós?\""
tlks_meet_aileen_3_a="\"Ah, desculpe, eu esqueci de te contar.\" A senhora continuou, \"Meu companheiro {u=tod} e eu somos ambos da Guilda de Aventureiros, nós acolhemos aventureiros do continente oriental. Talvez sua memória ainda não tenha se recuperado? Tudo isso deveria ter sido explicado na sua carta de convite.\""
tlks_meet_aileen_4_q="\"Onde nós estamos?\""
tlks_meet_aileen_4_a="\"Esta é a praia mais próxima de {s=41}. {s=41} não fica longe daqui. É lá que você deveria ter desembarcado. Vamos deixar as perguntas de lado por enquanto, tarefas importantes estão à nossa frente.\""
tlks_meet_aileen_5_q="\"Eu vim com vários aventureiros. Você os viu?\""
tlks_meet_aileen_5_a="\"Nós só encontramos você. Meu companheiro {u=tod} tem procurado por outros, mas até agora não encontrou pistas de onde eles possam estar. Devemos nos apressar para rastreá-los, pois muitos monstros vagueiam por esta faixa da costa.\" {u=aileen} explica ansiosamente, \"É melhor nos prepararmos para uma luta caso você queira salvar seus companheiros. Você está pronto?\""
tlks_meet_aileen_6_q="\"Sim, vamos partir agora mesmo. Não quero arriscar perder nenhum de meus amigos.\""
tlks_meet_aileen_7_q="\"Há algo mais que eu devo descobrir.\""
tlks_meet_aileen_7_a="\"Tudo bem, mas não temos tempo a perder.\""

tlks_meet_tod_1_a="\"{u=aileen}! Goblin!\" Um jovem guerreiro corre em sua direção com dois goblins seguindo atrás. Lanças voam por cima de seus ombros e se cravam no chão bem na sua frente."
tlks_meet_tod_2_q="Pegue suas armas!"
tlks_meet_tod_3_q="\"O quê? Quem é você?\""
tlks_meet_tod_3_a="\"Pare com essa conversa fiada, novato! Você pega o pequeno!\" O homem revira os olhos."

tlks_meet_tod_2_1_a="\"Esses malditos goblins!\" O jovem guerreiro deve ser o companheiro {u=tod} que {u=aileen} mencionou. Depois de xingar as pequenas bestas, {u=tod} relata os resultados de sua busca, \"Seus companheiros foram levados por uma matilha de goblins. Infelizmente, a maior parte deles já havia partido quando eu peguei o rastro. Matei dois, não, três deles. Os outros sem dúvida estão com seus amigos.\""
tlks_meet_tod_2_2_q="\"Como estão meus companheiros? Eles estão feridos?\""
tlks_meet_tod_2_2_a="\"Desculpe, não consegui vê-los claramente de tão longe. Eles ainda estavam de pé, então duvido que algum esteja gravemente ferido.\""
tlks_meet_tod_2_3_q="\"O que faremos agora?\""
tlks_meet_tod_2_3_a="\"Devemos nos dirigir imediatamente para {s=227}!\" {u=tod} diz apressadamente, \"Se tivermos sorte chegaremos a {s=227} a tempo de salvar seus companheiros.\""
tlks_meet_tod_2_4_q="\"Por que {s=227}?\""
tlks_meet_tod_2_4_a="\"Se eles estão indo naquela direção, só podem estar levando seus amigos para o covil deles em {s=227}. O lugar está cheio de goblins, mas a guilda não pode dispensar mão de obra para matá-los todos.\""
tlks_meet_tod_2_5_q="\"OK, vamos para {s=227}!\""

tlks_meet_thomas_1_a="Após a batalha, o homem que parece ser um soldado ou talvez um guarda sai da sala, \"Obrigado! Esses monstros certamente teriam arrombado a porta sem a sua ajuda.\""
tlks_meet_thomas_2_q="\"Nós somos aventureiros da Guilda de Aventureiros. O que aconteceu?\""
tlks_meet_thomas_2_a="\"Eu sou {u=thomas}, um dos guardas do banqueiro {u=brian}. Fomos emboscados a caminho de {s=76}. Meu companheiro, {u=william}, e eu fomos presos no prédio por monstros durante a evacuação.\""
tlks_meet_thomas_3_q="\"Quem são esses monstros?\""
tlks_meet_thomas_3_a="\"Eles são ladrões halflings!\" {u=thomas} responde amargamente, \"É estranho ver guerreiros esqueléticos e arqueiros esqueléticos presentes.\""
tlks_meet_thomas_4_q="\"Por que estranho? Eu pensei que fossem monstros comuns.\""
tlks_meet_thomas_4_a="\"Criaturas não-mortas fracas como esqueletos e zumbis não são raras, mas elas deveriam estar entre sua própria espécie miserável. Nunca vi esses demônios não-mortos trabalhando ao lado de raças civilizadas antes.\" {u=thomas} balança a cabeça exibindo um sorriso amargo, \"Não sei o que está acontecendo com este mundo.\""
tlks_meet_thomas_5_q="\"Então você conhece sobre os não-mortos?\""
tlks_meet_thomas_5_a="\"Haha! Eu não sou nenhum expert.\", {u=thomas} responde, \"Na verdade, meu tio era um clérigo e me ensinou algumas coisas sobre eles quando eu era menino. Táticas básicas como usar armas contundentes contra esqueletos. Como clérigo, ele até possuía a habilidade de banir os não-mortos, embora você não possa ensinar fé.\""
tlks_meet_thomas_6_q="\"Onde está o banqueiro, {u=brian}, agora?\""
tlks_meet_thomas_6_a="\"A maioria dos guardas escoltou {u=brian} durante a evacuação em direção a {s=138}. No entanto, com tantos inimigos por aí, tenho um mau pressentimento.\""
tlks_meet_thomas_7_q="\"Fomos enviados para investigar o que aconteceu e fornecer proteção.\""
tlks_meet_thomas_7_a="\"Graças a Deus! Eu estava desamparado agora, {u=william} estava seriamente ferido e deveria ser levado imediatamente para a cidade mais próxima. Como você busca resgatar {u=brian}, finalmente posso respirar aliviado e enviar {u=william} para a cidade agora.\""
tlks_meet_thomas_8_q="\"Apenas nos forneça todas as informações que você sabe. Por favor, seria de grande ajuda.\""
tlks_meet_thomas_8_a="\"Com certeza. {s=138} está aqui no mapa,\" {u=thomas} diz enquanto marca o local em nosso mapa de aventura. \"Além disso, eu tenho uma maça para você, caso você encontre esqueletos.\""
tlks_meet_thomas_9_q="\"Obrigado. Partiremos para o resgate imediatamente!\""
tlks_meet_thomas_10_q="\"Tenho outra pergunta.\""
tlks_meet_thomas_10_a="\"OK.\""

tlks_banker_thank_1_1_a="\"Obrigado! Nunca esperei que ajuda viesse.\" Ao transmitir o que aconteceu para {u=brian}, ele expressa solemnemente sua gratidão."
tlks_banker_thank_1_2_q="\"Só você sobreviveu em sua tropa?\""
tlks_banker_thank_1_2_a="\"Não tenho certeza. Fomos separados e havia tantos inimigos. Vários de meus guardas foram mortos e depois fui capturado pelos agressores.\""
tlks_banker_thank_1_3_q="\"Você sabe algo sobre esses agressores?\""
tlks_banker_thank_1_3_a="\"Não sei por que aqueles halflings teriam atacado minhas tropas. Não ouvi nada útil quando fui capturado, pois eles só falavam em sua própria língua.\""
tlks_banker_thank_1_4_q="\"Alguma coisa sobre aqueles esqueletos?\""
tlks_banker_thank_1_4_a="\"Ah, eu vi vários daqueles anões ordenando alguns esqueletos em língua comum. Eles seguravam um dispositivo estranho enquanto faziam isso. Algum artefato mágico que brilhava em um tom violeta maligno.\""
tlks_banker_thank_1_5_q="\"Nossa missão é escoltar você com segurança para {s=76}, vamos.\""

tlks_banker_thank_2_1_a="\"Finalmente, chegamos!\" {u=brian} respira fundo ao chegar ao portão, \"Não esperava que essa viagem para {s=76} fosse tão longa e perigosa. Devo me preparar para montar o primeiro banco no continente de Alrthia. Devo minha volta segura de meus guardas à sua Guilda de Aventureiros, muito obrigado!\""
tlks_banker_thank_2_2_q="\"Que serviços o banco oferece? Os aventureiros podem usá-lo?\""
tlks_banker_thank_2_2_a="\"Com certeza.\" {u=brian} parece revigorado ao falar sobre o banco. \"Tanto cidadãos cumpridores da lei quanto aventureiros corajosos têm direito a desfrutar de nossos serviços. Nossas caixas-fortes são a maneira mais segura de guardar seu ouro.\""
tlks_banker_thank_2_3_q="\"Qual cidade você tem em mente para o primeiro banco?\""
tlks_banker_thank_2_3_a="\"Ainda está em aberto, devemos considerar os resultados finais da investigação. Acho que pode ser uma das cidades maiores, se nada der errado.\""
tlks_banker_thank_2_4_q="\"Quantos bancos estão planejados para serem estabelecidos no continente de Alrthia?\""
tlks_banker_thank_2_4_a="\"Quanto mais, melhor!\" {u=brian} diz com um sorriso, \"Na verdade, depende. Algumas grandes cidades serão selecionadas para operação na fase inicial. Se tivermos um bom desempenho, gradualmente expandiremos para mais cidades.\""
tlks_banker_thank_2_5_q="\"Não há de quê, é nosso trabalho. Boa sorte e adeus.\""

qsts_1001_n="Procurando por Companheiros"
qsts_1001_d="Você acorda em uma praia estranha. Descobre que Lady {u=aileen}, membro da Guilda de Aventureiros, o salvou enquanto seus companheiros estavam desaparecidos.\n\nMuitos problemas ainda precisam ser resolvidos, o mais urgente é encontrar seus companheiros."
qsts_1001_1_n="Explorando a Costa"
qsts_1001_1_d="Pistas podem ser encontradas ao seguir a linha costeira em sua busca."
qsts_1001_1_msg="{ilu=beach_srch}Enquanto explora a costa, logo encontra alguns sinais óbvios de luta escritos na areia da praia. Você vê uma mistura de pegadas desordenadas, algumas do tamanho de humanos, mas a maioria menores.{p}Felizmente, após uma exploração mais detalhada, você faz uma descoberta: uma mochila enterrada na areia e algumas poções espalhadas, pertences de seus companheiros! Você usa as pegadas para determinar em que direção eles foram. Avante!"
qsts_1001_2_n="Seguindo em Frente"
qsts_1001_2_d="As pistas indicam que seus companheiros provavelmente foram levados por monstros que se escondem na área! Você deve encontrá-los antes que seja tarde demais."
qsts_1001_3_n="Covil dos Monstros"
qsts_1001_3_d="Seus companheiros foram levados por um bando de goblins. Você deve ir para o esconderijo deles {s=227} o mais rápido possível!"
qsts_1001_3_obj_str="Resgate seus companheiros em {s=227}"
qsts_1001_3_msg="{ilu=spikes}{s=227}, como o nome descreve, pode ser facilmente identificado mesmo a uma longa distância como esta.\n\nNo entanto, não há tempo para apreciar a paisagem. Você encontra aqueles malditos goblins do lado de fora do prédio!{p}Eles se reúnem em torno de uma estátua estranha preparando algo sem entrar na fortaleza, deixando seus companheiros praticamente desprotegidos.\n\nEste é o nosso momento! Com um aceno de cabeça, vocês se olham e puxam suas armas......."
qsts_1001_3_msg2="{ilu=outpost}Coragem e persistência finalmente dão frutos. Seus companheiros são resgatados com o mínimo de baixas. Deixe-os se recuperar nas cidades próximas e eles ficarão bons como novos.{p}{u=aileen} sugere que você vá para {s=26}.\n\n{s=26} é um posto avançado da Guilda de Aventureiros no continente oriental. {s=26} é um local ideal para descansar e reabastecer grupos de aventureiros. {u=aileen} cuidará para que você seja registrado na Guilda de Aventureiros para que possa acompanhá-los.{p}Embora você e seus companheiros possam ter muitas perguntas, como o que aconteceu com seu navio, você não tem tempo para refletir sobre elas.\n\nAventureiros estrangeiros naufragados em um continente estranho acharão que seguir o conselho de {u=aileen} é, sem dúvida, sua melhor e única opção neste momento."
qsts_1002_n="Posto Avançado"
qsts_1002_d="De acordo com {u=aileen}, você decide fazer uma pausa em {s=26}. Enquanto isso, {u=aileen} cuidará dos procedimentos para registrá-lo na Guilda de Aventureiros para o acompanhamento."

qsts_1003_n="Preparação Necessária"
qsts_1003_d="Habilidades de combate suficientes e suprimentos adequados são essenciais para uma equipe qualificada de aventureiros, não importa o que esteja à sua frente."

qsts_1004_n="Cadastro de Novato"
qsts_1004_d="{u=aileen} preparou os procedimentos necessários para você, e agora você pode se apresentar em {s=63}, a Sede da Guilda de Aventureiros."

qsts_1005_n="Prove sua Força"
qsts_1005_d="Bem-vindo à Guilda de Aventureiros!\n\nJá recebemos o relatório de {u=aileen}, muito obrigado por resolver essa crise! Como você sabe, um número anormalmente grande de monstros assola o continente, ferindo e matando inocentes. Essas bestas devem ser erradicadas com a máxima urgência.\n\nNo entanto, antes de atribuir quaisquer missões importantes, nossas regras exigem que enviemos equipes em algumas missões rotineiras para testar sua fibra. Isso é para garantir que eles possam lidar com as dificuldades da vida de aventureiro.\n\nDica:\nO valor de reputação da equipe de aventureiros pode ser aumentado ao completar tarefas da cidade, enquanto peças de ouro podem ser obtidas de várias maneiras, como comércio ou exploração de masmorras, etc.."

qsts_1006_n="Vá em Aventuras"
qsts_1006_d="Muito bem! Você provou ser uma equipe qualificada de aventureiros.\n\nAgora, a guilda tem algumas outras missões tutoriais para ajudá-lo a aprender mais sobre as habilidades necessárias para os aventureiros. À medida que sua equipe cresce, você receberá mais missões da guilda no futuro.\n\nClaro, não há pressa para concluir essas missões. Mais importante, agora você pode ir em aventuras e desenvolver sua equipe livremente!\n\n<c=o>(Este jogo está atualmente em fase de Acesso Antecipado e mais conteúdo será adicionado continuamente! Agradecemos novamente pelo seu apoio.\n\n-- Low Magic Studios)</c>"

qsts_1007_n="O Banqueiro Desaparecido"
qsts_1007_d="Um banqueiro bem conhecido chamado {u=brian} foi recentemente convidado para nossa terra. Ele ainda não chegou ao seu destino em {s=76}, mas já está vários dias atrasado. Flores viajava com uma escolta formidável de guardas, mas à luz das recentes atividades de monstros, achamos necessário enviar alguém para investigar o atraso.\n\nO melhor ponto de partida para sua busca foi marcado no mapa. Por favor, dirija-se para lá o mais rápido possível. Sua missão é escoltar {u=brian} de volta para {s=76} em segurança."
qsts_1007_1_n="Procurando pelo Banqueiro"
qsts_1007_1_d="Os detalhes da situação não estão claros, no entanto, você deve ir para o local alvo o mais rápido possível."
qsts_1007_1_msg="{ilu=broken_carriage}Ao chegar ao local designado, você encontra as ruínas de uma caravana. Você vê uma carruagem quebrada e suprimentos espalhados. No entanto, não há sinal do banqueiro ou de seus companheiros.{p}Após uma busca mais detalhada da área, nenhum outro indício valioso é descoberto.\n\nAgora você só pode ampliar o escopo da busca investigando outros locais suspeitos próximos."

qsts_1007_2_n="Ampliando o Escopo"
qsts_1007_2_d="O banqueiro e seus companheiros estão desaparecidos, você decide investigar lugares suspeitos próximos."
qsts_1007_2_msg="{ilu=outdoor_monsters}Ao se aproximar da cabana selvagem, você pode ouvir o burburinho de atividade.\n\nAo se aproximar, você avista vários ladrões halflings e dois esqueleto na frente da cabana!{p}Nesse mesmo momento, os monstros o avistam e atacam!"
qsts_1007_2_false_dst_msg="<f=b7>Nenhum rastro do banqueiro ou de seus companheiros.</f>"

qsts_1007_3_n="O Hálito da Morte"
qsts_1007_3_d="Você obtém notícias mais informativas, mas também mais preocupantes, de um dos guardas do banqueiro. Agora você deve ir ao destino e resgatar {u=brian}."
qsts_1007_3_msg="{ilu=breath_of_death}Com as informações obtidas de {u=thomas}, você continua a busca. Os sinais de luta, bem como os restos não enterrados dos combatentes, gradualmente o levam a {s=138}.{p}Ao entrar na masmorra, você detecta o fedor podre de decomposição e vê fragmentos esqueléticos espalhados pelo chão de pedra. Uma sensação sinistra o obriga a sair imediatamente.{p}No entanto, todos os indícios parecem indicar que {u=brian} provavelmente está sendo mantido prisioneiro lá dentro. Você não tem muitas opções neste momento. De acordo com o conselho de {u=thomas}, a melhor ação é preparar as armas ou meios certos para combater a iminente ameaça de mortos-vivos."

qsts_1007_4_n="Cavando Fundo"
qsts_1007_4_d="O banqueiro provavelmente está preso em {s=138}! Pegue seu martelo, esmague cada monstro, arrombe cada porta de cela e salve {u=brian}!"
qsts_1007_4_obj_str="Procurando e resgatando o banqueiro"
qsts_1007_4_msg="{ilu=assassin_escape}Quando você se prepara para limpar o campo de batalha e resgatar {u=brian}, uma explosão ensurdecedora ressoa atrás de você, deixando toda a sala envolta em uma densa fumaça...{p}Quando o gás sufocante se dissipa, você percebe, chocado, que o corpo do líder assassino desapareceu!{p}Depois disso, você vasculha minuciosamente tanto a sala quanto as áreas ao redor. Você encontra alguns saques deixados pelo inimigo, bem como uma carta, mas nenhuma outra informação útil.{p}No entanto, o resgate bem-sucedido de um inocente é uma grande vitória! Além disso, ele pode saber de algo."

qsts_1007_5_n="Escolta"
qsts_1007_5_d="Apesar dessa vitória, não há dúvida de que outros precisam de ajuda. Não podemos nos distrair. Com uma ameaça desconhecida à espreita na escuridão, devemos escoltar {u=brian} para {s=76} o mais rápido possível."

qsts_1008_n="Chaveiro de Final de Semana"
qsts_1008_d="Você recebeu vários baús sem dono da guilda. Se você conseguir abri-los com segurança, os itens dentro serão seus.\n\nTenha um ou dois membros da equipe treinando para aprender a habilidade de Abrir Fechaduras. Isso será útil para suas futuras aventuras.\n\nAlém disso, você precisará comprar algumas chaves-mestras pelo caminho."

qsts_1009_n="Ferramentas Melhores"
qsts_1009_d="Usar as perícias Desativar Dispositivo e Abrir Fechadura requer várias ferramentas.\n\nEmbora o conjunto de ferramentas simples seja apenas utilizável, ele é basicamente para iniciantes. Para profissionais, um conjunto de ferramentas de ladrão decentes ou até mesmo um conjunto de ferramentas de obra-prima são essenciais."

qsts_1010_n="A Habilidade Essencial"
qsts_1010_d="Para aventureiros, a perícia Desativar Dispositivo pode ser uma habilidade crucial de vida ou morte para exploração de masmorras. Não é nada sábio adentrar uma masmorra cheia de armadilhas sem aprender essa perícia.\n\nRecomenda-se que vários membros do grupo com alta Inteligência aprendam essa perícia."

qsts_1011_n="A Luta dos Artesãos"
qsts_1011_d="A Guilda de Artesãos próxima enfrentou alguns contratempos sérios e está pedindo ajuda à Guilda de Aventureiros. Seu grupo foi enviado para ajudá-los."
qsts_1011_1_n="Situação Urgente"
qsts_1011_1_d="Vá até a localização da Guilda de Artesãos o mais rápido possível!"
qsts_1011_2_n="Restabelecimento do Fornecimento de Recursos"
qsts_1011_2_d="No momento, o maior problema que os artesãos enfrentam é uma séria escassez de matérias-primas. Isso ocorre porque os locais de recursos estão ocupados por monstros. Por favor, recupere alguns desses locais o mais rápido possível para resolver essa necessidade urgente."
qsts_1011_3_n="Ajudar os Outros até o Fim"
qsts_1011_3_d="Os locais de recursos foram recuperados com sucesso, mas a lacuna no fornecimento de matérias-primas é muito grande. A Guilda de Artesãos pede que você ajude a coletar algumas matérias-primas urgentemente necessárias.\n\nA Guilda de Artesãos oferece serviços de treinamento para perícias relacionadas."
qsts_1011_4_n="Coleta de Recursos"
qsts_1011_4_d="Em geral, vários tipos de matérias-primas precisam ser coletados em diferentes locais de recursos. Às vezes, no entanto, uma pequena quantidade de outros tipos de matérias-primas também pode ser encontrada nesses locais."

qsts_1012_n="Artesão Habilidoso"
qsts_1012_d="Embora aventureiros comuns possam encontrar equipamentos comuns em praticamente qualquer lugar, equipamentos mais adequados ou de alta qualidade não são tão fáceis de obter.\n\nApós ajudar com sucesso a Guilda de Artesãos a resolver uma série de problemas, a Guilda de Aventureiros decidiu que você aprenderá várias perícias de fabricação de equipamentos com a Guilda de Artesãos para ajudar a resolver o problema de escassez de equipamentos de novos aventureiros."
qsts_1012_1_n="Aço e Fogo"
qsts_1012_1_d="Equipamentos de qualidade vêm de materiais de qualidade! Familiarizar-se com o trabalho artesanal de vários materiais é um curso obrigatório para se tornar um artesão qualificado."
qsts_1012_2_n="Espírito do Artesão"
qsts_1012_2_d="Fabrique um lote de equipamentos de alta qualidade e entregue-os à Guilda de Aventureiros."

-- z_add_qst.2
